// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: LexerPKM.jflex

package com.example.proyecto1_compi1.analizador.pkm;

import java_cup.runtime.Symbol;


@SuppressWarnings("fallthrough")
public class LexerPKM implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING_STATE = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\0"+
    "\1\6\1\7\1\10\3\0\1\11\1\12\2\0\1\13"+
    "\1\14\1\15\1\16\3\17\1\20\6\17\1\21\1\0"+
    "\1\22\1\23\1\24\1\0\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\37\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\37\1\54\1\37\1\55"+
    "\1\56\1\57\1\60\1\61\1\0\1\62\1\63\1\64"+
    "\1\65\1\66\1\67\1\70\1\71\1\72\1\37\1\73"+
    "\1\74\1\75\1\76\1\77\1\100\1\37\1\101\1\102"+
    "\1\103\1\104\2\37\1\105\1\106\1\107\1\110\1\111"+
    "\1\112\7\0\1\3\73\0\1\37\7\0\1\37\3\0"+
    "\1\37\3\0\1\37\1\0\1\37\6\0\1\37\1\0"+
    "\1\37\4\0\1\37\7\0\1\37\3\0\1\37\3\0"+
    "\1\37\1\0\1\37\6\0\1\37\1\0\1\37\u012b\0"+
    "\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\1\1\4\1\1\1\5"+
    "\1\6\1\1\1\7\1\10\1\1\1\11\1\12\16\13"+
    "\1\14\1\15\1\16\2\17\1\20\4\0\1\21\14\0"+
    "\20\13\1\0\1\22\32\0\10\13\1\23\1\13\1\24"+
    "\6\13\40\0\1\13\1\25\4\13\1\26\10\13\36\0"+
    "\1\27\10\0\1\30\3\13\1\31\2\13\1\32\1\33"+
    "\3\13\1\34\1\35\1\36\7\0\1\37\1\40\1\41"+
    "\23\0\1\42\1\0\1\43\1\0\1\44\5\0\1\45"+
    "\1\13\1\46\1\47\1\50\1\13\1\51\1\52\1\13"+
    "\6\0\1\53\1\54\1\0\1\55\1\0\1\56\1\0"+
    "\1\57\4\0\1\60\1\0\1\61\2\0\1\62\5\0"+
    "\1\63\1\64\1\0\1\65\1\13\1\66\1\67\12\0"+
    "\1\70\1\71\2\0\1\72\4\0\1\73\1\0\1\13"+
    "\11\0\1\74\1\0\1\75\1\76\1\0\1\77\1\0"+
    "\1\13\5\0\1\100\1\101\1\102\1\0\1\103\1\0"+
    "\1\104\1\0\1\105\1\0\1\106\1\0\1\107\1\110"+
    "\1\111\1\0\1\112";

  private static int [] zzUnpackAction() {
    int [] result = new int[360];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\113\0\226\0\341\0\226\0\u012c\0\u0177\0\u01c2"+
    "\0\226\0\u020d\0\u0258\0\u020d\0\226\0\u02a3\0\226\0\226"+
    "\0\u02ee\0\u0339\0\u0384\0\u03cf\0\u041a\0\u0465\0\u04b0\0\u04fb"+
    "\0\u0546\0\u0591\0\u05dc\0\u0627\0\u0672\0\u06bd\0\226\0\226"+
    "\0\226\0\226\0\u0708\0\u0753\0\u079e\0\u07e9\0\u0834\0\u087f"+
    "\0\226\0\u08ca\0\u0915\0\u0960\0\u09ab\0\u09f6\0\u0a41\0\u0a8c"+
    "\0\u0ad7\0\u0b22\0\u0b6d\0\u0bb8\0\u0c03\0\u0c4e\0\u0c99\0\u0ce4"+
    "\0\u0d2f\0\u0d7a\0\u0dc5\0\u0e10\0\u0e5b\0\u0ea6\0\u0ef1\0\u0f3c"+
    "\0\u0f87\0\u0fd2\0\u101d\0\u1068\0\u10b3\0\u10fe\0\226\0\u1149"+
    "\0\u1194\0\u11df\0\u122a\0\u1275\0\u12c0\0\u130b\0\u1356\0\u13a1"+
    "\0\u13ec\0\u1437\0\u1482\0\u14cd\0\u1518\0\u1563\0\u15ae\0\u15f9"+
    "\0\u1644\0\u168f\0\u16da\0\u1725\0\u1770\0\u17bb\0\u1806\0\u1851"+
    "\0\u189c\0\u18e7\0\u1932\0\u197d\0\u19c8\0\u1a13\0\u1a5e\0\u1aa9"+
    "\0\u1af4\0\u02ee\0\u1b3f\0\u02ee\0\u1b8a\0\u1bd5\0\u1c20\0\u1c6b"+
    "\0\u1cb6\0\u1d01\0\u1d4c\0\u1d97\0\u1de2\0\u1e2d\0\u1e78\0\u1ec3"+
    "\0\u1f0e\0\u1f59\0\u1fa4\0\u1fef\0\u203a\0\u2085\0\u20d0\0\u211b"+
    "\0\u2166\0\u21b1\0\u21fc\0\u2247\0\u2292\0\u22dd\0\u2328\0\u2373"+
    "\0\u23be\0\u2409\0\u2454\0\u249f\0\u24ea\0\u2535\0\u2580\0\u25cb"+
    "\0\u2616\0\u2661\0\u26ac\0\u02ee\0\u26f7\0\u2742\0\u278d\0\u27d8"+
    "\0\u02ee\0\u2823\0\u286e\0\u28b9\0\u2904\0\u294f\0\u299a\0\u29e5"+
    "\0\u2a30\0\u2a7b\0\u2ac6\0\u2b11\0\u2b5c\0\u2ba7\0\u2bf2\0\u2c3d"+
    "\0\u2c88\0\u2cd3\0\u2d1e\0\u2d69\0\u2db4\0\u2dff\0\u2e4a\0\u2e95"+
    "\0\u2ee0\0\u2f2b\0\u2f76\0\u2fc1\0\u300c\0\u3057\0\u30a2\0\u30ed"+
    "\0\u3138\0\u3183\0\u31ce\0\u3219\0\u3264\0\u32af\0\u32fa\0\226"+
    "\0\u3345\0\u3390\0\u33db\0\u3426\0\u3471\0\u34bc\0\u3507\0\u3552"+
    "\0\u02ee\0\u359d\0\u35e8\0\u3633\0\u02ee\0\u367e\0\u36c9\0\u02ee"+
    "\0\u02ee\0\u3714\0\u375f\0\u37aa\0\226\0\226\0\226\0\u37f5"+
    "\0\u3840\0\u388b\0\u38d6\0\u3921\0\u396c\0\u39b7\0\226\0\226"+
    "\0\226\0\u3a02\0\u3a4d\0\u3a98\0\u3ae3\0\u3b2e\0\u3b79\0\u3bc4"+
    "\0\u3c0f\0\u3c5a\0\u3ca5\0\u3cf0\0\u3d3b\0\u3d86\0\u3dd1\0\u3e1c"+
    "\0\u3e67\0\u3eb2\0\u3efd\0\u3f48\0\226\0\u3f93\0\226\0\u3fde"+
    "\0\226\0\u4029\0\u4074\0\u40bf\0\u410a\0\u4155\0\226\0\u41a0"+
    "\0\u02ee\0\u02ee\0\u02ee\0\u41eb\0\u02ee\0\226\0\u4236\0\u4281"+
    "\0\u42cc\0\u4317\0\u4362\0\u43ad\0\u43f8\0\226\0\226\0\u4443"+
    "\0\226\0\u448e\0\226\0\u44d9\0\226\0\u4524\0\u456f\0\u45ba"+
    "\0\u4605\0\226\0\u4650\0\226\0\u469b\0\u46e6\0\226\0\u4731"+
    "\0\u477c\0\u47c7\0\u4812\0\u485d\0\226\0\226\0\u48a8\0\u02ee"+
    "\0\u48f3\0\226\0\226\0\u493e\0\u4989\0\u49d4\0\u4a1f\0\u4a6a"+
    "\0\u4ab5\0\u4b00\0\u4b4b\0\u4b96\0\u4be1\0\226\0\226\0\u4c2c"+
    "\0\u4c77\0\226\0\u4cc2\0\u4d0d\0\u4d58\0\u4da3\0\226\0\u4dee"+
    "\0\u4e39\0\u4e84\0\u4ecf\0\u4f1a\0\u4f65\0\u4fb0\0\u4ffb\0\u5046"+
    "\0\u5091\0\u50dc\0\226\0\u5127\0\226\0\226\0\u5172\0\226"+
    "\0\u51bd\0\u5208\0\u5253\0\u529e\0\u52e9\0\u5334\0\u537f\0\226"+
    "\0\226\0\226\0\u53ca\0\226\0\u5415\0\226\0\u5460\0\u02ee"+
    "\0\u54ab\0\226\0\u54f6\0\226\0\226\0\226\0\u5541\0\226";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[360];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\0\2\4\1\5\1\6\1\7\1\10"+
    "\1\3\1\11\1\12\1\3\1\13\2\14\1\15\1\16"+
    "\1\17\1\20\1\3\1\21\1\22\1\23\1\24\2\21"+
    "\1\25\5\21\1\26\2\21\1\27\1\30\1\31\3\21"+
    "\1\32\1\33\4\3\3\21\1\34\2\21\1\35\12\21"+
    "\1\36\5\21\1\37\1\3\1\40\2\41\1\42\1\41"+
    "\1\43\1\41\1\42\16\41\1\44\30\41\1\45\34\41"+
    "\114\0\2\4\1\0\2\4\114\0\1\46\7\0\2\47"+
    "\5\0\6\47\26\0\6\47\23\0\2\7\1\0\1\7"+
    "\1\0\106\7\17\0\2\50\111\0\2\14\116\0\1\51"+
    "\104\0\1\52\2\53\42\0\1\54\1\55\1\56\1\57"+
    "\1\60\4\0\1\61\1\62\1\0\1\63\2\0\1\64"+
    "\1\65\26\0\2\21\5\0\27\21\4\0\27\21\22\0"+
    "\2\21\5\0\13\21\1\66\13\21\4\0\27\21\22\0"+
    "\2\21\5\0\23\21\1\67\3\21\4\0\27\21\22\0"+
    "\2\21\5\0\1\70\15\21\1\71\10\21\4\0\27\21"+
    "\22\0\2\21\5\0\20\21\1\72\6\21\4\0\27\21"+
    "\22\0\2\21\5\0\16\21\1\73\10\21\4\0\27\21"+
    "\22\0\2\21\5\0\23\21\1\74\3\21\4\0\27\21"+
    "\22\0\2\21\5\0\4\21\1\75\22\21\4\0\27\21"+
    "\22\0\2\21\5\0\1\76\11\21\1\77\3\21\1\100"+
    "\10\21\4\0\27\21\22\0\2\21\5\0\7\21\1\101"+
    "\17\21\4\0\27\21\22\0\2\21\5\0\4\21\1\102"+
    "\22\21\4\0\27\21\22\0\2\21\5\0\27\21\4\0"+
    "\16\21\1\103\10\21\22\0\2\21\5\0\27\21\4\0"+
    "\1\21\1\104\25\21\22\0\2\21\5\0\27\21\4\0"+
    "\11\21\1\105\15\21\5\0\1\42\165\0\1\106\35\0"+
    "\2\41\3\0\1\41\1\107\104\41\7\0\1\110\122\0"+
    "\2\111\5\0\6\111\26\0\6\111\36\0\1\112\3\0"+
    "\2\50\156\0\1\113\1\114\1\115\5\0\1\116\1\117"+
    "\1\0\1\120\2\0\1\121\1\122\22\0\1\123\1\0"+
    "\1\124\1\0\2\53\154\0\1\125\14\0\1\126\112\0"+
    "\1\127\114\0\1\130\105\0\1\131\115\0\1\132\105\0"+
    "\1\133\124\0\1\134\106\0\1\135\100\0\1\136\14\0"+
    "\1\137\71\0\1\140\3\0\1\141\43\0\2\21\5\0"+
    "\1\142\22\21\1\143\3\21\4\0\27\21\22\0\2\21"+
    "\5\0\20\21\1\144\6\21\4\0\27\21\22\0\2\21"+
    "\5\0\21\21\1\145\5\21\4\0\27\21\22\0\2\21"+
    "\5\0\22\21\1\146\4\21\4\0\27\21\22\0\2\21"+
    "\5\0\4\21\1\147\22\21\4\0\27\21\22\0\2\21"+
    "\5\0\15\21\1\150\11\21\4\0\27\21\22\0\2\21"+
    "\5\0\20\21\1\151\6\21\4\0\27\21\22\0\2\21"+
    "\5\0\3\21\1\152\23\21\4\0\27\21\22\0\2\21"+
    "\5\0\15\21\1\153\11\21\4\0\27\21\22\0\2\21"+
    "\5\0\26\21\1\154\4\0\27\21\22\0\2\21\5\0"+
    "\13\21\1\155\13\21\4\0\27\21\22\0\2\21\5\0"+
    "\10\21\1\156\16\21\4\0\27\21\22\0\2\21\5\0"+
    "\13\21\1\157\13\21\4\0\27\21\22\0\2\21\5\0"+
    "\27\21\4\0\13\21\1\160\13\21\22\0\2\21\5\0"+
    "\27\21\4\0\14\21\1\161\12\21\22\0\2\21\5\0"+
    "\27\21\4\0\26\21\1\162\24\0\1\163\1\164\70\0"+
    "\7\110\1\165\103\110\17\0\2\166\5\0\6\166\26\0"+
    "\6\166\42\0\2\167\171\0\1\170\114\0\1\171\105\0"+
    "\1\172\110\0\1\173\124\0\1\174\106\0\1\175\100\0"+
    "\1\176\14\0\1\177\71\0\1\200\3\0\1\201\43\0"+
    "\2\202\111\0\2\203\156\0\1\204\127\0\1\205\105\0"+
    "\1\206\1\0\1\207\113\0\1\210\101\0\1\211\122\0"+
    "\1\212\112\0\1\213\110\0\1\214\104\0\1\215\110\0"+
    "\1\216\7\0\1\217\124\0\1\220\67\0\1\221\134\0"+
    "\1\222\24\0\2\21\5\0\2\21\1\223\24\21\4\0"+
    "\27\21\22\0\2\21\5\0\4\21\1\224\22\21\4\0"+
    "\27\21\22\0\2\21\5\0\21\21\1\225\5\21\4\0"+
    "\27\21\22\0\2\21\5\0\7\21\1\226\17\21\4\0"+
    "\27\21\22\0\2\21\5\0\22\21\1\227\4\21\4\0"+
    "\27\21\22\0\2\21\5\0\4\21\1\230\22\21\4\0"+
    "\27\21\22\0\2\21\5\0\16\21\1\231\10\21\4\0"+
    "\27\21\22\0\2\21\5\0\17\21\1\232\7\21\4\0"+
    "\27\21\22\0\2\21\5\0\21\21\1\233\5\21\4\0"+
    "\27\21\22\0\2\21\5\0\10\21\1\234\16\21\4\0"+
    "\27\21\22\0\2\21\5\0\22\21\1\235\4\21\4\0"+
    "\27\21\22\0\2\21\5\0\13\21\1\236\13\21\4\0"+
    "\27\21\22\0\2\21\5\0\27\21\4\0\16\21\1\237"+
    "\10\21\22\0\2\21\5\0\27\21\4\0\11\21\1\240"+
    "\15\21\22\0\2\21\5\0\27\21\4\0\5\21\1\241"+
    "\21\21\14\0\1\242\1\243\45\0\1\244\3\0\1\245"+
    "\4\0\1\246\10\0\1\247\6\0\1\250\21\0\1\251"+
    "\1\0\1\164\77\0\1\252\122\0\2\253\5\0\6\253"+
    "\26\0\6\253\36\0\1\254\3\0\2\167\170\0\1\255"+
    "\113\0\1\256\101\0\1\257\122\0\1\260\110\0\1\261"+
    "\104\0\1\262\110\0\1\263\7\0\1\264\124\0\1\265"+
    "\67\0\1\266\134\0\1\267\20\0\1\270\1\0\1\271"+
    "\1\0\2\202\105\0\1\123\3\0\2\203\165\0\1\272"+
    "\104\0\1\273\124\0\1\274\116\0\1\275\107\0\1\276"+
    "\107\0\1\277\120\0\1\300\75\0\1\301\127\0\1\302"+
    "\105\0\1\303\117\0\1\304\75\0\1\305\120\0\1\306"+
    "\112\0\1\307\121\0\1\310\26\0\2\21\5\0\12\21"+
    "\1\311\14\21\4\0\27\21\22\0\2\21\5\0\10\21"+
    "\1\312\16\21\4\0\27\21\22\0\2\21\5\0\4\21"+
    "\1\313\22\21\4\0\27\21\22\0\2\21\5\0\4\21"+
    "\1\314\22\21\4\0\27\21\22\0\2\21\5\0\15\21"+
    "\1\315\11\21\4\0\27\21\22\0\2\21\5\0\13\21"+
    "\1\316\13\21\4\0\27\21\22\0\2\21\5\0\27\21"+
    "\4\0\1\317\26\21\22\0\2\21\5\0\3\21\1\320"+
    "\23\21\4\0\27\21\22\0\2\21\5\0\4\21\1\321"+
    "\22\21\4\0\27\21\22\0\2\21\5\0\16\21\1\322"+
    "\10\21\4\0\27\21\22\0\2\21\5\0\27\21\4\0"+
    "\20\21\1\323\6\21\22\0\2\21\5\0\27\21\4\0"+
    "\13\21\1\324\13\21\22\0\2\21\2\0\1\325\2\0"+
    "\27\21\4\0\27\21\14\0\1\242\45\0\1\326\45\0"+
    "\1\243\44\0\1\327\113\0\1\330\114\0\1\331\116\0"+
    "\1\332\106\0\1\333\3\0\1\334\6\0\1\335\5\0"+
    "\1\336\66\0\1\337\31\0\1\250\21\0\1\251\36\0"+
    "\1\340\42\0\1\341\122\0\2\342\5\0\6\342\26\0"+
    "\6\342\42\0\2\343\175\0\1\344\107\0\1\345\107\0"+
    "\1\346\103\0\1\347\127\0\1\350\105\0\1\351\117\0"+
    "\1\352\75\0\1\353\120\0\1\354\112\0\1\355\121\0"+
    "\1\356\26\0\2\357\111\0\2\360\162\0\1\361\110\0"+
    "\1\362\125\0\1\363\77\0\1\364\47\0\1\365\155\0"+
    "\1\366\50\0\1\367\160\0\1\370\43\0\1\371\161\0"+
    "\1\372\104\0\1\373\114\0\1\374\112\0\1\375\31\0"+
    "\1\376\15\0\1\377\106\0\2\21\5\0\24\21\1\u0100"+
    "\2\21\4\0\27\21\22\0\2\21\5\0\3\21\1\u0101"+
    "\23\21\4\0\27\21\22\0\2\21\5\0\3\21\1\u0102"+
    "\23\21\4\0\27\21\22\0\2\21\5\0\4\21\1\u0103"+
    "\22\21\4\0\27\21\22\0\2\21\5\0\21\21\1\u0104"+
    "\5\21\4\0\27\21\22\0\2\21\5\0\25\21\1\u0105"+
    "\1\21\4\0\27\21\22\0\2\21\2\0\1\u0106\2\0"+
    "\27\21\4\0\27\21\22\0\2\21\5\0\27\21\4\0"+
    "\25\21\1\u0107\1\21\24\0\1\u0108\174\0\1\330\71\0"+
    "\1\u0109\115\0\1\u010a\126\0\1\u010b\103\0\1\u010c\102\0"+
    "\1\u010d\47\0\2\u010e\5\0\6\u010e\26\0\6\u010e\35\0"+
    "\1\u010f\4\0\2\343\160\0\1\u0110\50\0\1\u0111\154\0"+
    "\1\u0112\50\0\1\u0113\160\0\1\u0114\44\0\1\u0115\160\0"+
    "\1\u0116\104\0\1\u0117\114\0\1\u0118\112\0\1\u0119\50\0"+
    "\1\u011a\103\0\1\u011b\1\0\2\357\3\0\1\u011c\101\0"+
    "\1\270\3\0\2\360\173\0\1\u011d\112\0\1\u011e\34\0"+
    "\1\u011f\165\0\1\u0120\112\0\1\u0121\114\0\1\u0122\111\0"+
    "\1\u0123\116\0\1\u0124\33\0\1\u0125\111\0\1\u0126\171\0"+
    "\1\u0127\27\0\2\21\5\0\4\21\1\u0128\22\21\4\0"+
    "\27\21\22\0\2\21\5\0\4\21\1\u0129\22\21\4\0"+
    "\27\21\22\0\2\21\2\0\1\u012a\2\0\27\21\4\0"+
    "\27\21\62\0\1\u012b\134\0\1\u012c\32\0\1\u012d\163\0"+
    "\1\u012e\114\0\1\u012f\117\0\1\u0130\107\0\1\u0131\112\0"+
    "\1\u0132\114\0\1\u0133\111\0\1\u0134\116\0\1\u0135\33\0"+
    "\1\u0136\112\0\1\u0137\105\0\2\u0138\171\0\1\u0139\26\0"+
    "\1\u013a\202\0\1\u013b\112\0\1\u013c\103\0\1\u013d\114\0"+
    "\1\u013e\37\0\1\u013f\161\0\1\u0140\37\0\2\21\5\0"+
    "\20\21\1\u0141\6\21\4\0\27\21\106\0\1\u0142\66\0"+
    "\1\326\132\0\1\u0143\101\0\1\u0144\40\0\1\u0145\4\0"+
    "\1\u0146\174\0\1\u0147\112\0\1\u0148\103\0\1\u0149\114\0"+
    "\1\u014a\40\0\1\u014b\105\0\2\u0138\3\0\1\u011c\172\0"+
    "\1\u014c\32\0\1\u014d\112\0\1\u014e\154\0\1\u014f\47\0"+
    "\1\u0150\176\0\1\u0151\22\0\2\21\5\0\10\21\1\u0152"+
    "\16\21\4\0\27\21\24\0\1\u0153\175\0\1\u0154\27\0"+
    "\1\u0155\110\0\2\u0156\111\0\2\u0157\36\0\1\u0158\57\0"+
    "\1\u0159\112\0\1\u015a\154\0\1\u015b\50\0\1\u015c\164\0"+
    "\1\u015d\37\0\1\u015e\155\0\1\u015f\43\0\2\21\5\0"+
    "\5\21\1\u0160\21\21\4\0\27\21\62\0\1\340\135\0"+
    "\1\u0161\67\0\1\327\52\0\2\u0156\36\0\1\u0162\52\0"+
    "\2\u0157\1\u0163\115\0\1\u0164\153\0\1\u0165\50\0\1\u0166"+
    "\110\0\1\u0167\150\0\1\u0168\112\0\1\337\33\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[21900];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\3\1\1\11\3\1\1\11"+
    "\1\1\2\11\16\1\4\11\2\1\4\0\1\11\14\0"+
    "\20\1\1\0\1\11\32\0\21\1\40\0\17\1\36\0"+
    "\1\11\10\0\14\1\3\11\7\0\3\11\23\0\1\11"+
    "\1\0\1\11\1\0\1\11\5\0\1\11\6\1\1\11"+
    "\1\1\6\0\2\11\1\0\1\11\1\0\1\11\1\0"+
    "\1\11\4\0\1\11\1\0\1\11\2\0\1\11\5\0"+
    "\2\11\1\0\2\1\2\11\12\0\2\11\2\0\1\11"+
    "\4\0\1\11\1\0\1\1\11\0\1\11\1\0\2\11"+
    "\1\0\1\11\1\0\1\1\5\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\1\1\1\0\1\11\1\0\3\11"+
    "\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[360];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }
    private StringBuilder stringBuffer = new StringBuilder();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerPKM(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* ignorar caracteres desconocidos */
            }
          // fall through
          case 75: break;
          case 2:
            { /* ignorar */
            }
          // fall through
          case 76: break;
          case 3:
            { stringBuffer.setLength(0); yybegin(STRING_STATE);
            }
          // fall through
          case 77: break;
          case 4:
            { /* comentario $ */
            }
          // fall through
          case 78: break;
          case 5:
            { return symbol(sym.COMMA);
            }
          // fall through
          case 79: break;
          case 6:
            { return symbol(sym.GUION);
            }
          // fall through
          case 80: break;
          case 7:
            { return symbol(sym.NUMBER, Integer.parseInt(yytext()));
            }
          // fall through
          case 81: break;
          case 8:
            { return symbol(sym.COLON);
            }
          // fall through
          case 82: break;
          case 9:
            { return symbol(sym.IGUAL);
            }
          // fall through
          case 83: break;
          case 10:
            { return symbol(sym.MAYOR_QUE);
            }
          // fall through
          case 84: break;
          case 11:
            { return symbol(sym.ID, yytext());
            }
          // fall through
          case 85: break;
          case 12:
            { return symbol(sym.LBRACE);
            }
          // fall through
          case 86: break;
          case 13:
            { return symbol(sym.RBRACE);
            }
          // fall through
          case 87: break;
          case 14:
            { stringBuffer.append(yytext());
            }
          // fall through
          case 88: break;
          case 15:
            { yybegin(YYINITIAL);
        return symbol(sym.STRING, stringBuffer.toString());
            }
          // fall through
          case 89: break;
          case 16:
            { stringBuffer.append('@');
            }
          // fall through
          case 90: break;
          case 17:
            { return symbol(sym.SLASH_CLOSE);
            }
          // fall through
          case 91: break;
          case 18:
            { stringBuffer.append('"');
            }
          // fall through
          case 92: break;
          case 19:
            { return symbol(sym.COLOR_NAME, "RED");
            }
          // fall through
          case 93: break;
          case 20:
            { return symbol(sym.COLOR_NAME, "SKY");
            }
          // fall through
          case 94: break;
          case 21:
            { return symbol(sym.COLOR_NAME, "BLUE");
            }
          // fall through
          case 95: break;
          case 22:
            { return symbol(sym.MONO);
            }
          // fall through
          case 96: break;
          case 23:
            { return symbol(sym.STYLE_FONT);
            }
          // fall through
          case 97: break;
          case 24:
            { return symbol(sym.COLOR_NAME, "BLACK");
            }
          // fall through
          case 98: break;
          case 25:
            { return symbol(sym.COLOR_NAME, "GREEN");
            }
          // fall through
          case 99: break;
          case 26:
            { return symbol(sym.SOLID);
            }
          // fall through
          case 100: break;
          case 27:
            { return symbol(sym.COLOR_NAME, "WHITE");
            }
          // fall through
          case 101: break;
          case 28:
            { return symbol(sym.SIZE_EQ);
            }
          // fall through
          case 102: break;
          case 29:
            { stringBuffer.append("🥲");
            }
          // fall through
          case 103: break;
          case 30:
            { stringBuffer.append("😀");
            }
          // fall through
          case 104: break;
          case 31:
            { stringBuffer.append("😐");
            }
          // fall through
          case 105: break;
          case 32:
            { stringBuffer.append("❤️");
            }
          // fall through
          case 106: break;
          case 33:
            { return symbol(sym.METADATA_BLOCK, yytext());
            }
          // fall through
          case 107: break;
          case 34:
            { return symbol(sym.DROP_TAG);
            }
          // fall through
          case 108: break;
          case 35:
            { return symbol(sym.LINE_OPEN);
            }
          // fall through
          case 109: break;
          case 36:
            { return symbol(sym.OPEN_TAG);
            }
          // fall through
          case 110: break;
          case 37:
            { return symbol(sym.TEXT_ELEMENT);
            }
          // fall through
          case 111: break;
          case 38:
            { return symbol(sym.DASHED);
            }
          // fall through
          case 112: break;
          case 39:
            { return symbol(sym.DOTTED);
            }
          // fall through
          case 113: break;
          case 40:
            { return symbol(sym.COLOR_NAME, "PURPLE");
            }
          // fall through
          case 114: break;
          case 41:
            { return symbol(sym.COLOR_NAME, "YELLOW");
            }
          // fall through
          case 115: break;
          case 42:
            { return symbol(sym.COLOR_EQ);
            }
          // fall through
          case 116: break;
          case 43:
            { return symbol(sym.HEX_COLOR, yytext());
            }
          // fall through
          case 117: break;
          case 44:
            { return symbol(sym.RGB_COLOR, yytext());
            }
          // fall through
          case 118: break;
          case 45:
            { return symbol(sym.DROP_CLOSE);
            }
          // fall through
          case 119: break;
          case 46:
            { return symbol(sym.LINE_CLOSE);
            }
          // fall through
          case 120: break;
          case 47:
            { return symbol(sym.OPEN_CLOSE);
            }
          // fall through
          case 121: break;
          case 48:
            { return symbol(sym.TEXT_CLOSE);
            }
          // fall through
          case 122: break;
          case 49:
            { return symbol(sym.HSL_COLOR, yytext());
            }
          // fall through
          case 123: break;
          case 50:
            { return symbol(sym.STYLE_COLOR);
            }
          // fall through
          case 124: break;
          case 51:
            { return symbol(sym.STYLE_OPEN);
            }
          // fall through
          case 125: break;
          case 52:
            { return symbol(sym.TABLE_OPEN);
            }
          // fall through
          case 126: break;
          case 53:
            { return symbol(sym.CURSIVE);
            }
          // fall through
          case 127: break;
          case 54:
            { return symbol(sym.FAMILY_EQ);
            }
          // fall through
          case 128: break;
          case 55:
            { stringBuffer.append("😺");
            }
          // fall through
          case 129: break;
          case 56:
            { return symbol(sym.STYLE_CLOSE);
            }
          // fall through
          case 130: break;
          case 57:
            { return symbol(sym.TABLE_CLOSE);
            }
          // fall through
          case 131: break;
          case 58:
            { return symbol(sym.STYLE_BORDER);
            }
          // fall through
          case 132: break;
          case 59:
            { return symbol(sym.SELECT_TAG);
            }
          // fall through
          case 133: break;
          case 60:
            { return symbol(sym.SELECT_CLOSE);
            }
          // fall through
          case 134: break;
          case 61:
            { return symbol(sym.CONTENT_OPEN);
            }
          // fall through
          case 135: break;
          case 62:
            { return symbol(sym.ELEMENT_OPEN);
            }
          // fall through
          case 136: break;
          case 63:
            { return symbol(sym.SECTION_OPEN);
            }
          // fall through
          case 137: break;
          case 64:
            { stringBuffer.append("⭐");
            }
          // fall through
          case 138: break;
          case 65:
            { return symbol(sym.CONTENT_CLOSE);
            }
          // fall through
          case 139: break;
          case 66:
            { return symbol(sym.ELEMENT_CLOSE);
            }
          // fall through
          case 140: break;
          case 67:
            { return symbol(sym.SECTION_CLOSE);
            }
          // fall through
          case 141: break;
          case 68:
            { return symbol(sym.MULTIPLE_TAG);
            }
          // fall through
          case 142: break;
          case 69:
            { return symbol(sym.SANS_SERIF);
            }
          // fall through
          case 143: break;
          case 70:
            { String txt = yytext();
        int n = Integer.parseInt(txt.substring(txt.indexOf("star-")+5, txt.lastIndexOf("]")));
        for (int i = 0; i < n; i++) stringBuffer.append("⭐");
            }
          // fall through
          case 144: break;
          case 71:
            { return symbol(sym.MULTIPLE_CLOSE);
            }
          // fall through
          case 145: break;
          case 72:
            { return symbol(sym.STYLE_BG);
            }
          // fall through
          case 146: break;
          case 73:
            { return symbol(sym.STYLE_TEXT);
            }
          // fall through
          case 147: break;
          case 74:
            { String txt = yytext();
        int n = Integer.parseInt(txt.substring(txt.indexOf("star:")+5, txt.lastIndexOf(":")));
        for (int i = 0; i < n; i++) stringBuffer.append("⭐");
            }
          // fall through
          case 148: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
