
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.proyecto1_compi1.analizador.pkm;

import java.util.*;
import com.example.proyecto1_compi1.modelo.forms.*;
import com.example.proyecto1_compi1.modelo.question.*;
import com.example.proyecto1_compi1.modelo.table.*;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserPKM extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserPKM() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserPKM(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserPKM(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\036\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\004\000\002\003\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\004\003\000\002\005\021\000\002\007\004\000\002" +
    "\007\003\000\002\010\003\000\002\011\011\000\002\021" +
    "\006\000\002\012\006\000\002\012\006\000\002\013\014" +
    "\000\002\013\014\000\002\014\016\000\002\014\016\000" +
    "\002\015\014\000\002\015\014\000\002\016\003\000\002" +
    "\016\005\000\002\017\003\000\002\017\005\000\002\020" +
    "\002\000\002\020\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\130\000\016\004\017\005\004\012\012\014\016\016" +
    "\021\020\011\001\002\000\004\033\103\001\002\000\016" +
    "\002\ufffd\005\ufffd\012\ufffd\014\ufffd\016\ufffd\020\ufffd\001" +
    "\002\000\016\002\ufffa\005\ufffa\012\ufffa\014\ufffa\016\ufffa" +
    "\020\ufffa\001\002\000\004\002\102\001\002\000\016\002" +
    "\uffff\005\004\012\012\014\016\016\021\020\011\001\002" +
    "\000\004\033\023\001\002\000\004\033\023\001\002\000" +
    "\016\002\ufffb\005\ufffb\012\ufffb\014\ufffb\016\ufffb\020\ufffb" +
    "\001\002\000\016\002\ufff8\005\ufff8\012\ufff8\014\ufff8\016" +
    "\ufff8\020\ufff8\001\002\000\016\002\ufff9\005\ufff9\012\ufff9" +
    "\014\ufff9\016\ufff9\020\ufff9\001\002\000\004\033\023\001" +
    "\002\000\014\005\004\012\012\014\016\016\021\020\011" +
    "\001\002\000\016\002\ufffc\005\ufffc\012\ufffc\014\ufffc\016" +
    "\ufffc\020\ufffc\001\002\000\004\033\023\001\002\000\004" +
    "\032\027\001\002\000\004\022\024\001\002\000\004\033" +
    "\025\001\002\000\004\022\026\001\002\000\004\032\ufff2" +
    "\001\002\000\004\022\030\001\002\000\004\025\031\001" +
    "\002\000\004\032\032\001\002\000\006\022\uffe9\026\uffe9" +
    "\001\002\000\006\022\034\026\035\001\002\000\004\032" +
    "\047\001\002\000\004\022\036\001\002\000\004\025\037" +
    "\001\002\000\004\033\040\001\002\000\006\022\uffe7\026" +
    "\uffe7\001\002\000\006\022\042\026\043\001\002\000\004" +
    "\033\046\001\002\000\006\017\044\031\045\001\002\000" +
    "\016\002\uffec\005\uffec\012\uffec\014\uffec\016\uffec\020\uffec" +
    "\001\002\000\016\002\uffed\005\uffed\012\uffed\014\uffed\016" +
    "\uffed\020\uffed\001\002\000\006\022\uffe6\026\uffe6\001\002" +
    "\000\006\022\uffe8\026\uffe8\001\002\000\016\002\001\005" +
    "\004\012\012\014\016\016\021\020\011\001\002\000\016" +
    "\002\ufffe\005\ufffe\012\ufffe\014\ufffe\016\ufffe\020\ufffe\001" +
    "\002\000\004\032\053\001\002\000\004\022\054\001\002" +
    "\000\004\025\055\001\002\000\004\032\032\001\002\000" +
    "\006\022\034\026\057\001\002\000\004\022\060\001\002" +
    "\000\004\033\061\001\002\000\006\015\063\031\062\001" +
    "\002\000\016\002\uffef\005\uffef\012\uffef\014\uffef\016\uffef" +
    "\020\uffef\001\002\000\016\002\uffee\005\uffee\012\uffee\014" +
    "\uffee\016\uffee\020\uffee\001\002\000\004\032\065\001\002" +
    "\000\006\013\067\031\066\001\002\000\016\002\ufff1\005" +
    "\ufff1\012\ufff1\014\ufff1\016\ufff1\020\ufff1\001\002\000\016" +
    "\002\ufff0\005\ufff0\012\ufff0\014\ufff0\016\ufff0\020\ufff0\001" +
    "\002\000\004\032\071\001\002\000\004\022\072\001\002" +
    "\000\004\025\073\001\002\000\004\032\032\001\002\000" +
    "\006\022\034\026\075\001\002\000\004\022\076\001\002" +
    "\000\004\033\077\001\002\000\006\021\100\031\101\001" +
    "\002\000\016\002\uffea\005\uffea\012\uffea\014\uffea\016\uffea" +
    "\020\uffea\001\002\000\016\002\uffeb\005\uffeb\012\uffeb\014" +
    "\uffeb\016\uffeb\020\uffeb\001\002\000\004\002\000\001\002" +
    "\000\004\022\104\001\002\000\004\033\105\001\002\000" +
    "\004\022\106\001\002\000\004\033\107\001\002\000\004" +
    "\022\110\001\002\000\004\033\111\001\002\000\004\022" +
    "\112\001\002\000\004\034\113\001\002\000\004\030\114" +
    "\001\002\000\004\007\115\001\002\000\004\011\116\001" +
    "\002\000\004\033\125\001\002\000\006\010\ufff5\011\ufff5" +
    "\001\002\000\006\010\122\011\116\001\002\000\006\010" +
    "\ufff4\011\ufff4\001\002\000\004\006\124\001\002\000\006" +
    "\010\ufff6\011\ufff6\001\002\000\016\002\ufff7\005\ufff7\012" +
    "\ufff7\014\ufff7\016\ufff7\020\ufff7\001\002\000\004\022\126" +
    "\001\002\000\004\033\127\001\002\000\004\022\130\001" +
    "\002\000\004\032\131\001\002\000\004\031\132\001\002" +
    "\000\006\010\ufff3\011\ufff3\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\130\000\022\002\006\003\007\004\004\005\017\012" +
    "\012\013\005\014\014\015\013\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\016\004\050\005\017\012\012\013\005\014\014\015\013" +
    "\001\001\000\004\021\067\001\001\000\004\021\063\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\021\051\001\001\000\020\003\047\004\004\005" +
    "\017\012\012\013\005\014\014\015\013\001\001\000\002" +
    "\001\001\000\004\021\021\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\016" +
    "\032\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\017" +
    "\040\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\016\004\050" +
    "\005\017\012\012\013\005\014\014\015\013\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\016\055\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\016\073\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\007\117\010\116\011\120\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\010\122" +
    "\011\120\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserPKM$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserPKM$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserPKM$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



  @Override
  public void report_error(String message, Object info) {
      StringBuilder m = new StringBuilder("\nERROR SINTÁCTICO\n");
      if (info instanceof Symbol) {
          Symbol s = (Symbol) info;
          m.append("Mensaje: ").append(message).append("\n");
          m.append("Línea: ").append(s.left + 1).append("\n");
          m.append("Columna: ").append(s.right + 1).append("\n");
          m.append("Token: ").append(s.value).append("\n");
          m.append("Código token: ").append(s.sym).append("\n");
      } else {
          m.append("Mensaje: ").append(message);
      }
      System.err.println(m.toString());
  }

  @Override
  public void report_fatal_error(String message, Object info) {
      report_error(message, info);
      throw new RuntimeException("Parsing detenido");
  }

  @Override
  public void syntax_error(Symbol cur_token) {
      System.err.println("\nTOKEN INESPERADO:");
      System.err.println("Línea: " + (cur_token.left + 1));
      System.err.println("Columna: " + (cur_token.right + 1));
      System.err.println("Token: " + cur_token.value);
  }

  @Override
  public void unrecovered_syntax_error(Symbol cur_token) {
      throw new RuntimeException("Error sintactico en linea: " + (cur_token.left + 1) +
          ", columna: " + (cur_token.right + 1) + ", token: " + cur_token.value);
  }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserPKM$actions {
  private final ParserPKM parser;

  /** Constructor */
  CUP$ParserPKM$actions(ParserPKM parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserPKM$do_action_part00000000(
    int                        CUP$ParserPKM$act_num,
    java_cup.runtime.lr_parser CUP$ParserPKM$parser,
    java.util.Stack            CUP$ParserPKM$stack,
    int                        CUP$ParserPKM$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserPKM$result;

      /* select the action based on the action number */
      switch (CUP$ParserPKM$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // pkm_file ::= METADATA_BLOCK elementos_principales 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("pkm_file",0, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= pkm_file EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).value;
		RESULT = start_val;
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserPKM$parser.done_parsing();
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // pkm_file ::= elementos_principales 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("pkm_file",0, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // elementos_principales ::= elementos_principales elemento_principal 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elementos_principales",1, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // elementos_principales ::= elemento_principal 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elementos_principales",1, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // elemento_principal ::= section 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).right;
		SectionsModel s = (SectionsModel)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.peek()).value;
		
        if (ResultParser.currentForm != null) ResultParser.currentForm.addElement(s);
        if (ResultParser.formsModel  != null) ResultParser.formsModel.addElement(s);
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento_principal",2, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // elemento_principal ::= open_question 
            {
              Object RESULT =null;
		int qleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).left;
		int qright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).right;
		OpenQuestion q = (OpenQuestion)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.peek()).value;
		
        if (ResultParser.currentForm != null) ResultParser.currentForm.addElement(q);
        if (ResultParser.formsModel  != null) ResultParser.formsModel.addElement(q);
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento_principal",2, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // elemento_principal ::= select_question 
            {
              Object RESULT =null;
		int qleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).left;
		int qright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).right;
		SelectQuestion q = (SelectQuestion)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.peek()).value;
		
        if (ResultParser.currentForm != null) ResultParser.currentForm.addElement(q);
        if (ResultParser.formsModel  != null) ResultParser.formsModel.addElement(q);
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento_principal",2, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // elemento_principal ::= multiple_question 
            {
              Object RESULT =null;
		int qleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).left;
		int qright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).right;
		MultipleQuestion q = (MultipleQuestion)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.peek()).value;
		
        if (ResultParser.currentForm != null) ResultParser.currentForm.addElement(q);
        if (ResultParser.formsModel  != null) ResultParser.formsModel.addElement(q);
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento_principal",2, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // elemento_principal ::= drop_question 
            {
              Object RESULT =null;
		int qleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).left;
		int qright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).right;
		DropQuestion q = (DropQuestion)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.peek()).value;
		
        if (ResultParser.currentForm != null) ResultParser.currentForm.addElement(q);
        if (ResultParser.formsModel  != null) ResultParser.formsModel.addElement(q);
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento_principal",2, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // section ::= SECTION_OPEN NUMBER COMMA NUMBER COMMA NUMBER COMMA NUMBER COMMA ID MAYOR_QUE CONTENT_OPEN content CONTENT_CLOSE SECTION_CLOSE 
            {
              SectionsModel RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-13)).left;
		int wright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-13)).right;
		Integer w = (Integer)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-13)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-11)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-11)).right;
		Integer h = (Integer)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-11)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-9)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-9)).right;
		Integer x = (Integer)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-9)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-7)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-7)).right;
		Integer y = (Integer)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-7)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-5)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-5)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).value;
		
        /*
         * Construimos la lista de PropertyItem que SectionsModel
         * necesita en su constructor.
         */
        ArrayList<PropertyItem> props = new ArrayList<>();
        props.add(new PropertyItem("width",       w));
        props.add(new PropertyItem("height",      h));
        props.add(new PropertyItem("pointX",      x));
        props.add(new PropertyItem("pointY",      y));
        /*
         * El quinto campo (ID) se guarda como "orientation".
         * SectionsModel llama Orientation.valueOf() sobre este
         * string, así que el lexer debe producir "VERTICAL" o
         * "HORIZONTAL".  Si el ID es el nombre de la sección,
         * cambia la clave a "name" aquí.
         */
        props.add(new PropertyItem("orientation", id.toString()));
        /*
         * Los elementos internos van como propiedad "elements".
         * c es un ArrayList<Object> acumulado por la regla content.
         */
        props.add(new PropertyItem("elements", c));

        RESULT = new SectionsModel(props);
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("section",3, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-14)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // content ::= content element 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.peek()).value;
		
        ArrayList<Object> list = (ArrayList<Object>) c;
        list.add(e);
        RESULT = list;
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("content",5, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // content ::= element 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.peek()).value;
		
        ArrayList<Object> list = new ArrayList<>();
        list.add(e);
        RESULT = list;
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("content",5, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // element ::= text_element 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).right;
		TextModel t = (TextModel)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.peek()).value;
		 RESULT = t; 
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("element",6, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // text_element ::= TEXT_ELEMENT NUMBER COMMA NUMBER COMMA STRING SLASH_CLOSE 
            {
              TextModel RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-5)).left;
		int wright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-5)).right;
		Integer w = (Integer)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-5)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-3)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-3)).right;
		Integer h = (Integer)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).value;
		
        TextModel text = new TextModel();
        text.addProperty(new PropertyItem("width",  w));
        text.addProperty(new PropertyItem("height", h));
        /*
         * TextModel.addProperty maneja "content" y "label".
         * Usa "label" si el parser .form guardó el texto con LABEL;
         * cámbialo a "content" si lo guardó con CONTENT.
         */
        text.addProperty(new PropertyItem("label",  s.toString().replace("\"", "").trim()));
        RESULT = text;
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("text_element",7, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-6)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // parametros_pregunta ::= NUMBER COMMA NUMBER COMMA 
            {
              ArrayList<PropertyItem> RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-3)).left;
		int wright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-3)).right;
		Integer w = (Integer)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-3)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).right;
		Integer h = (Integer)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).value;
		
        ArrayList<PropertyItem> props = new ArrayList<>();
        props.add(new PropertyItem("width",  w));
        props.add(new PropertyItem("height", h));
        RESULT = props;
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("parametros_pregunta",15, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-3)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // open_question ::= OPEN_TAG parametros_pregunta STRING SLASH_CLOSE 
            {
              OpenQuestion RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).right;
		ArrayList<PropertyItem> p = (ArrayList<PropertyItem>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).value;
		
        OpenQuestion open = new OpenQuestion();
        for (PropertyItem prop : p) open.addProperty(prop);
        String label = s.toString().replace("\"", "").trim();
        open.addProperty(new PropertyItem("label", label));
        RESULT = open;
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("open_question",8, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-3)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // open_question ::= OPEN_TAG parametros_pregunta STRING OPEN_CLOSE 
            {
              OpenQuestion RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).right;
		ArrayList<PropertyItem> p = (ArrayList<PropertyItem>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).value;
		
        OpenQuestion open = new OpenQuestion();
        for (PropertyItem prop : p) open.addProperty(prop);
        String label = s.toString().replace("\"", "").trim();
        open.addProperty(new PropertyItem("label", label));
        RESULT = open;
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("open_question",8, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-3)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // select_question ::= SELECT_TAG parametros_pregunta STRING COMMA LBRACE options RBRACE COMMA NUMBER SLASH_CLOSE 
            {
              SelectQuestion RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-8)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-8)).right;
		ArrayList<PropertyItem> p = (ArrayList<PropertyItem>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-8)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-7)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-7)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-7)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-4)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-4)).right;
		ArrayList<String> o = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-4)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).value;
		
        SelectQuestion select = new SelectQuestion();
        for (PropertyItem prop : p) select.addProperty(prop);
        select.addProperty(new PropertyItem("label",   s.toString()));
        select.addProperty(new PropertyItem("options", o));
        ArrayList<Integer> correct = new ArrayList<>();
        correct.add(n);
        select.addProperty(new PropertyItem("correct", correct));
        RESULT = select;
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("select_question",9, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-9)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // select_question ::= SELECT_TAG parametros_pregunta STRING COMMA LBRACE options RBRACE COMMA NUMBER SELECT_CLOSE 
            {
              SelectQuestion RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-8)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-8)).right;
		ArrayList<PropertyItem> p = (ArrayList<PropertyItem>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-8)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-7)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-7)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-7)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-4)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-4)).right;
		ArrayList<String> o = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-4)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).value;
		
        SelectQuestion select = new SelectQuestion();
        for (PropertyItem prop : p) select.addProperty(prop);
        select.addProperty(new PropertyItem("label",   s.toString()));
        select.addProperty(new PropertyItem("options", o));
        ArrayList<Integer> correct = new ArrayList<>();
        correct.add(n);
        select.addProperty(new PropertyItem("correct", correct));
        RESULT = select;
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("select_question",9, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-9)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // multiple_question ::= MULTIPLE_TAG parametros_pregunta STRING COMMA LBRACE options RBRACE COMMA LBRACE int_list RBRACE SLASH_CLOSE 
            {
              MultipleQuestion RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-10)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-10)).right;
		ArrayList<PropertyItem> p = (ArrayList<PropertyItem>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-10)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-9)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-9)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-9)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-6)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-6)).right;
		ArrayList<String> o = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-6)).value;
		int clleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).left;
		int clright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).right;
		ArrayList<Integer> cl = (ArrayList<Integer>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).value;
		
        MultipleQuestion multiple = new MultipleQuestion();
        for (PropertyItem prop : p) multiple.addProperty(prop);
        multiple.addProperty(new PropertyItem("label",   s.toString()));
        multiple.addProperty(new PropertyItem("options", o));
        multiple.addProperty(new PropertyItem("correct", cl));
        RESULT = multiple;
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("multiple_question",10, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-11)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // multiple_question ::= MULTIPLE_TAG parametros_pregunta STRING COMMA LBRACE options RBRACE COMMA LBRACE int_list RBRACE MULTIPLE_CLOSE 
            {
              MultipleQuestion RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-10)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-10)).right;
		ArrayList<PropertyItem> p = (ArrayList<PropertyItem>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-10)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-9)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-9)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-9)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-6)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-6)).right;
		ArrayList<String> o = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-6)).value;
		int clleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).left;
		int clright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).right;
		ArrayList<Integer> cl = (ArrayList<Integer>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).value;
		
        MultipleQuestion multiple = new MultipleQuestion();
        for (PropertyItem prop : p) multiple.addProperty(prop);
        multiple.addProperty(new PropertyItem("label",   s.toString()));
        multiple.addProperty(new PropertyItem("options", o));
        multiple.addProperty(new PropertyItem("correct", cl));
        RESULT = multiple;
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("multiple_question",10, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-11)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // drop_question ::= DROP_TAG parametros_pregunta STRING COMMA LBRACE options RBRACE COMMA NUMBER SLASH_CLOSE 
            {
              DropQuestion RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-8)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-8)).right;
		ArrayList<PropertyItem> p = (ArrayList<PropertyItem>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-8)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-7)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-7)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-7)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-4)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-4)).right;
		ArrayList<String> o = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-4)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).value;
		
        DropQuestion drop = new DropQuestion();
        for (PropertyItem prop : p) drop.addProperty(prop);
        drop.addProperty(new PropertyItem("label",   s.toString()));
        drop.addProperty(new PropertyItem("options", o));
        ArrayList<Integer> correct = new ArrayList<>();
        correct.add(n);
        drop.addProperty(new PropertyItem("correct", correct));
        RESULT = drop;
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("drop_question",11, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-9)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // drop_question ::= DROP_TAG parametros_pregunta STRING COMMA LBRACE options RBRACE COMMA NUMBER DROP_CLOSE 
            {
              DropQuestion RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-8)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-8)).right;
		ArrayList<PropertyItem> p = (ArrayList<PropertyItem>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-8)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-7)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-7)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-7)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-4)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-4)).right;
		ArrayList<String> o = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-4)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).value;
		
        DropQuestion drop = new DropQuestion();
        for (PropertyItem prop : p) drop.addProperty(prop);
        drop.addProperty(new PropertyItem("label",   s.toString()));
        drop.addProperty(new PropertyItem("options", o));
        ArrayList<Integer> correct = new ArrayList<>();
        correct.add(n);
        drop.addProperty(new PropertyItem("correct", correct));
        RESULT = drop;
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("drop_question",11, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-9)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // options ::= STRING 
            {
              ArrayList<String> RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.peek()).value;
		
        ArrayList<String> list = new ArrayList<>();
        list.add(s.toString());
        RESULT = list;
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("options",12, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // options ::= options COMMA STRING 
            {
              ArrayList<String> RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).right;
		ArrayList<String> o = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.peek()).value;
		
        o.add(s.toString());
        RESULT = o;
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("options",12, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // int_list ::= NUMBER 
            {
              ArrayList<Integer> RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.peek()).value;
		
        ArrayList<Integer> list = new ArrayList<>();
        list.add(n);
        RESULT = list;
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("int_list",13, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // int_list ::= int_list COMMA NUMBER 
            {
              ArrayList<Integer> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).right;
		ArrayList<Integer> l = (ArrayList<Integer>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.peek()).value;
		
        l.add(n);
        RESULT = l;
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("int_list",13, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // int_list_opt ::= 
            {
              ArrayList<Integer> RESULT =null;
		
        RESULT = new ArrayList<Integer>();
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("int_list_opt",14, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // int_list_opt ::= int_list 
            {
              ArrayList<Integer> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).right;
		ArrayList<Integer> l = (ArrayList<Integer>)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.peek()).value;
		
        RESULT = l;
    
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("int_list_opt",14, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserPKM$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserPKM$do_action(
    int                        CUP$ParserPKM$act_num,
    java_cup.runtime.lr_parser CUP$ParserPKM$parser,
    java.util.Stack            CUP$ParserPKM$stack,
    int                        CUP$ParserPKM$top)
    throws java.lang.Exception
    {
              return CUP$ParserPKM$do_action_part00000000(
                               CUP$ParserPKM$act_num,
                               CUP$ParserPKM$parser,
                               CUP$ParserPKM$stack,
                               CUP$ParserPKM$top);
    }
}

}
