
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.proyecto1_compi1.analizador.pkm;

import java.util.*;
import com.example.proyecto1_compi1.modelo.forms.*;
import com.example.proyecto1_compi1.modelo.question.*;
import com.example.proyecto1_compi1.modelo.table.*;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserPKM extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserPKM() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserPKM(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserPKM(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\037\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\004\000\002\003\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\004\003\000\002\005\011\000\002\022\013\000\002" +
    "\006\004\000\002\006\003\000\002\007\003\000\002\010" +
    "\011\000\002\011\006\000\002\011\006\000\002\012\014" +
    "\000\002\012\014\000\002\013\016\000\002\013\016\000" +
    "\002\014\014\000\002\014\014\000\002\023\006\000\002" +
    "\016\003\000\002\016\005\000\002\020\003\000\002\020" +
    "\005\000\002\021\002\000\002\021\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\131\000\016\004\017\005\004\012\012\014\016\016" +
    "\021\020\011\001\002\000\004\033\103\001\002\000\016" +
    "\002\ufffd\005\ufffd\012\ufffd\014\ufffd\016\ufffd\020\ufffd\001" +
    "\002\000\016\002\ufffa\005\ufffa\012\ufffa\014\ufffa\016\ufffa" +
    "\020\ufffa\001\002\000\004\002\102\001\002\000\016\002" +
    "\uffff\005\004\012\012\014\016\016\021\020\011\001\002" +
    "\000\004\033\023\001\002\000\004\033\023\001\002\000" +
    "\016\002\ufffb\005\ufffb\012\ufffb\014\ufffb\016\ufffb\020\ufffb" +
    "\001\002\000\016\002\ufff8\005\ufff8\012\ufff8\014\ufff8\016" +
    "\ufff8\020\ufff8\001\002\000\016\002\ufff9\005\ufff9\012\ufff9" +
    "\014\ufff9\016\ufff9\020\ufff9\001\002\000\004\033\023\001" +
    "\002\000\014\005\004\012\012\014\016\016\021\020\011" +
    "\001\002\000\016\002\ufffc\005\ufffc\012\ufffc\014\ufffc\016" +
    "\ufffc\020\ufffc\001\002\000\004\033\023\001\002\000\004" +
    "\032\027\001\002\000\004\022\024\001\002\000\004\033" +
    "\025\001\002\000\004\022\026\001\002\000\004\032\uffe9" +
    "\001\002\000\004\022\030\001\002\000\004\025\031\001" +
    "\002\000\004\032\032\001\002\000\006\022\uffe8\026\uffe8" +
    "\001\002\000\006\022\034\026\035\001\002\000\004\032" +
    "\047\001\002\000\004\022\036\001\002\000\004\025\037" +
    "\001\002\000\004\033\040\001\002\000\006\022\uffe6\026" +
    "\uffe6\001\002\000\006\022\042\026\043\001\002\000\004" +
    "\033\046\001\002\000\006\017\044\031\045\001\002\000" +
    "\016\002\uffec\005\uffec\012\uffec\014\uffec\016\uffec\020\uffec" +
    "\001\002\000\016\002\uffed\005\uffed\012\uffed\014\uffed\016" +
    "\uffed\020\uffed\001\002\000\006\022\uffe5\026\uffe5\001\002" +
    "\000\006\022\uffe7\026\uffe7\001\002\000\016\002\001\005" +
    "\004\012\012\014\016\016\021\020\011\001\002\000\016" +
    "\002\ufffe\005\ufffe\012\ufffe\014\ufffe\016\ufffe\020\ufffe\001" +
    "\002\000\004\032\053\001\002\000\004\022\054\001\002" +
    "\000\004\025\055\001\002\000\004\032\032\001\002\000" +
    "\006\022\034\026\057\001\002\000\004\022\060\001\002" +
    "\000\004\033\061\001\002\000\006\015\063\031\062\001" +
    "\002\000\016\002\uffef\005\uffef\012\uffef\014\uffef\016\uffef" +
    "\020\uffef\001\002\000\016\002\uffee\005\uffee\012\uffee\014" +
    "\uffee\016\uffee\020\uffee\001\002\000\004\032\065\001\002" +
    "\000\006\013\067\031\066\001\002\000\016\002\ufff1\005" +
    "\ufff1\012\ufff1\014\ufff1\016\ufff1\020\ufff1\001\002\000\016" +
    "\002\ufff0\005\ufff0\012\ufff0\014\ufff0\016\ufff0\020\ufff0\001" +
    "\002\000\004\032\071\001\002\000\004\022\072\001\002" +
    "\000\004\025\073\001\002\000\004\032\032\001\002\000" +
    "\006\022\034\026\075\001\002\000\004\022\076\001\002" +
    "\000\004\033\077\001\002\000\006\021\100\031\101\001" +
    "\002\000\016\002\uffea\005\uffea\012\uffea\014\uffea\016\uffea" +
    "\020\uffea\001\002\000\016\002\uffeb\005\uffeb\012\uffeb\014" +
    "\uffeb\016\uffeb\020\uffeb\001\002\000\004\002\000\001\002" +
    "\000\004\022\124\001\002\000\004\030\105\001\002\000" +
    "\004\007\106\001\002\000\004\011\107\001\002\000\004" +
    "\033\116\001\002\000\006\010\ufff4\011\ufff4\001\002\000" +
    "\006\010\113\011\107\001\002\000\006\010\ufff3\011\ufff3" +
    "\001\002\000\004\006\115\001\002\000\006\010\ufff5\011" +
    "\ufff5\001\002\000\016\002\ufff7\005\ufff7\012\ufff7\014\ufff7" +
    "\016\ufff7\020\ufff7\001\002\000\004\022\117\001\002\000" +
    "\004\033\120\001\002\000\004\022\121\001\002\000\004" +
    "\032\122\001\002\000\004\031\123\001\002\000\006\010" +
    "\ufff2\011\ufff2\001\002\000\004\033\125\001\002\000\004" +
    "\022\126\001\002\000\004\033\127\001\002\000\004\022" +
    "\130\001\002\000\004\033\131\001\002\000\004\022\132" +
    "\001\002\000\004\034\133\001\002\000\004\030\ufff6\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\131\000\022\002\006\003\007\004\004\005\017\011" +
    "\012\012\005\013\014\014\013\001\001\000\004\022\103" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\016\004\050\005\017\011\012\012\005\013\014" +
    "\014\013\001\001\000\004\023\067\001\001\000\004\023" +
    "\063\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\023\051\001\001\000\020\003\047\004" +
    "\004\005\017\011\012\012\005\013\014\014\013\001\001" +
    "\000\002\001\001\000\004\023\021\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\016\032\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\020\040\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\016" +
    "\004\050\005\017\011\012\012\005\013\014\014\013\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\016\055\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\016" +
    "\073\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\006\110\007\107\010\111\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\007\113" +
    "\010\111\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserPKM$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserPKM$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserPKM$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



  @Override
  public void report_error(String message, Object info) {
      StringBuilder m = new StringBuilder("\nERROR SINTÁCTICO\n");
      if (info instanceof Symbol) {
          Symbol s = (Symbol) info;
          m.append("Mensaje: ").append(message).append("\n");
          m.append("Línea: ").append(s.left + 1).append("\n");
          m.append("Columna: ").append(s.right + 1).append("\n");
          m.append("Token: ").append(s.value).append("\n");
          m.append("Código token: ").append(s.sym).append("\n");
      } else {
          m.append("Mensaje: ").append(message);
      }
      System.err.println(m.toString());
  }

  @Override
  public void report_fatal_error(String message, Object info) {
      report_error(message, info);
      throw new RuntimeException("Parsing detenido");
  }

  @Override
  public void syntax_error(Symbol cur_token) {
      System.err.println("\nTOKEN INESPERADO:");
      System.err.println("Línea: " + (cur_token.left + 1));
      System.err.println("Columna: " + (cur_token.right + 1));
      System.err.println("Token: " + cur_token.value);
  }

  @Override
  public void unrecovered_syntax_error(Symbol cur_token) {
      throw new RuntimeException("Error sintactico en linea: " + (cur_token.left +1) +
          ", columna: " + (cur_token.right + 1 ) + ", token: " + cur_token.value);
  }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserPKM$actions {
  private final ParserPKM parser;

  /** Constructor */
  CUP$ParserPKM$actions(ParserPKM parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserPKM$do_action_part00000000(
    int                        CUP$ParserPKM$act_num,
    java_cup.runtime.lr_parser CUP$ParserPKM$parser,
    java.util.Stack            CUP$ParserPKM$stack,
    int                        CUP$ParserPKM$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserPKM$result;

      /* select the action based on the action number */
      switch (CUP$ParserPKM$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // pkm_file ::= METADATA_BLOCK elementos_principales 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("pkm_file",0, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= pkm_file EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).value;
		RESULT = start_val;
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserPKM$parser.done_parsing();
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // pkm_file ::= elementos_principales 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("pkm_file",0, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // elementos_principales ::= elementos_principales elemento_principal 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elementos_principales",1, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // elementos_principales ::= elemento_principal 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elementos_principales",1, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // elemento_principal ::= section 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento_principal",2, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // elemento_principal ::= open_question 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento_principal",2, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // elemento_principal ::= select_question 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento_principal",2, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // elemento_principal ::= multiple_question 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento_principal",2, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // elemento_principal ::= drop_question 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento_principal",2, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // section ::= SECTION_OPEN parametros_seccion MAYOR_QUE CONTENT_OPEN content CONTENT_CLOSE SECTION_CLOSE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("section",3, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-6)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // parametros_seccion ::= NUMBER COMMA NUMBER COMMA NUMBER COMMA NUMBER COMMA ID 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("parametros_seccion",16, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-8)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // content ::= content element 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("content",4, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // content ::= element 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("content",4, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // element ::= text_element 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("element",5, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // text_element ::= TEXT_ELEMENT NUMBER COMMA NUMBER COMMA STRING SLASH_CLOSE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("text_element",6, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-6)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // open_question ::= OPEN_TAG parametros_pregunta STRING SLASH_CLOSE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("open_question",7, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-3)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // open_question ::= OPEN_TAG parametros_pregunta STRING OPEN_CLOSE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("open_question",7, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-3)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // select_question ::= SELECT_TAG parametros_pregunta STRING COMMA LBRACE options RBRACE COMMA NUMBER SLASH_CLOSE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("select_question",8, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-9)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // select_question ::= SELECT_TAG parametros_pregunta STRING COMMA LBRACE options RBRACE COMMA NUMBER SELECT_CLOSE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("select_question",8, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-9)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // multiple_question ::= MULTIPLE_TAG parametros_pregunta STRING COMMA LBRACE options RBRACE COMMA LBRACE int_list RBRACE SLASH_CLOSE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("multiple_question",9, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-11)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // multiple_question ::= MULTIPLE_TAG parametros_pregunta STRING COMMA LBRACE options RBRACE COMMA LBRACE int_list RBRACE MULTIPLE_CLOSE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("multiple_question",9, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-11)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // drop_question ::= DROP_TAG parametros_pregunta STRING COMMA LBRACE options RBRACE COMMA NUMBER SLASH_CLOSE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("drop_question",10, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-9)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // drop_question ::= DROP_TAG parametros_pregunta STRING COMMA LBRACE options RBRACE COMMA NUMBER DROP_CLOSE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("drop_question",10, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-9)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // parametros_pregunta ::= NUMBER COMMA NUMBER COMMA 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("parametros_pregunta",17, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-3)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // options ::= STRING 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("options",12, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // options ::= options COMMA STRING 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("options",12, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // int_list ::= NUMBER 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("int_list",14, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // int_list ::= int_list COMMA NUMBER 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("int_list",14, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // int_list_opt ::= 
            {
              Object RESULT =null;
		
                    ArrayList<Integer> list = new ArrayList<Integer>();
                    RESULT = list;
                
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("int_list_opt",15, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // int_list_opt ::= int_list 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("int_list_opt",15, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserPKM$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserPKM$do_action(
    int                        CUP$ParserPKM$act_num,
    java_cup.runtime.lr_parser CUP$ParserPKM$parser,
    java.util.Stack            CUP$ParserPKM$stack,
    int                        CUP$ParserPKM$top)
    throws java.lang.Exception
    {
              return CUP$ParserPKM$do_action_part00000000(
                               CUP$ParserPKM$act_num,
                               CUP$ParserPKM$parser,
                               CUP$ParserPKM$stack,
                               CUP$ParserPKM$top);
    }
}

}
