
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.proyecto1_compi1.analizador.pkm;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONTENT_OPEN = 5;
  public static final int GUION = 18;
  public static final int IGUAL = 21;
  public static final int RBRACE = 20;
  public static final int MULTIPLE_TAG = 12;
  public static final int TEXT_ELEMENT = 7;
  public static final int SELECT_TAG = 10;
  public static final int DROP_TAG = 14;
  public static final int MAYOR_QUE = 22;
  public static final int LBRACE = 19;
  public static final int COLON = 17;
  public static final int ID = 26;
  public static final int STRING = 24;
  public static final int SELECT_CLOSE = 11;
  public static final int COMMA = 16;
  public static final int SECTION_OPEN = 3;
  public static final int SLASH_CLOSE = 23;
  public static final int NUMBER = 25;
  public static final int EOF = 0;
  public static final int SECTION_CLOSE = 4;
  public static final int METADATA_BLOCK = 2;
  public static final int CONTENT_CLOSE = 6;
  public static final int error = 1;
  public static final int DROP_CLOSE = 15;
  public static final int MULTIPLE_CLOSE = 13;
  public static final int OPEN_TAG = 8;
  public static final int OPEN_CLOSE = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "METADATA_BLOCK",
  "SECTION_OPEN",
  "SECTION_CLOSE",
  "CONTENT_OPEN",
  "CONTENT_CLOSE",
  "TEXT_ELEMENT",
  "OPEN_TAG",
  "OPEN_CLOSE",
  "SELECT_TAG",
  "SELECT_CLOSE",
  "MULTIPLE_TAG",
  "MULTIPLE_CLOSE",
  "DROP_TAG",
  "DROP_CLOSE",
  "COMMA",
  "COLON",
  "GUION",
  "LBRACE",
  "RBRACE",
  "IGUAL",
  "MAYOR_QUE",
  "SLASH_CLOSE",
  "STRING",
  "NUMBER",
  "ID"
  };
}

