// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexer.jflex

package com.example.proyecto1_compi1.analizador;


import java_cup.runtime.Symbol;
import java.util.ArrayList;
import com.example.proyecto1_compi1.token.Token;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\1\5\1\0\1\6\1\7\1\10\1\0\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\12\21\1\22"+
    "\1\23\1\24\1\25\1\26\2\0\1\27\1\30\1\31"+
    "\1\32\1\33\2\34\1\35\1\36\2\34\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\2\34\1\51\1\52\1\34\1\53\1\0\1\54\1\55"+
    "\1\56\1\0\1\57\1\60\1\61\1\62\1\63\1\34"+
    "\1\64\1\65\1\66\2\34\1\67\1\70\1\71\1\72"+
    "\1\73\1\34\1\74\1\75\1\76\1\77\1\34\1\100"+
    "\1\34\1\101\1\34\1\102\1\103\1\104\1\105\6\0"+
    "\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\1\1\2\1\3\1\1\1\4"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\6\21\1\22\1\23\1\24"+
    "\11\21\1\25\1\1\1\26\1\27\1\30\1\0\1\31"+
    "\1\32\1\0\1\33\1\34\1\35\23\21\1\36\1\37"+
    "\36\21\1\40\2\21\1\41\17\21\1\42\1\43\1\21"+
    "\1\44\7\21\1\45\1\46\1\47\5\21\1\50\1\21"+
    "\1\51\1\52\1\53\1\54\1\21\1\55\1\56\3\21"+
    "\1\57\2\21\1\60\4\21\1\61\20\21\1\62\1\21"+
    "\1\63\4\21\1\64\1\21\1\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[187];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\106\0\214\0\322\0\u0118\0\u015e\0\106\0\u01a4"+
    "\0\106\0\106\0\106\0\106\0\106\0\106\0\106\0\u01ea"+
    "\0\106\0\106\0\u0230\0\u0276\0\u02bc\0\u0302\0\u0348\0\u038e"+
    "\0\u03d4\0\u041a\0\u0460\0\106\0\106\0\106\0\u04a6\0\u04ec"+
    "\0\u0532\0\u0578\0\u05be\0\u0604\0\u064a\0\u0690\0\u06d6\0\106"+
    "\0\u071c\0\106\0\106\0\106\0\u0118\0\106\0\106\0\u0762"+
    "\0\106\0\106\0\106\0\u07a8\0\u07ee\0\u0834\0\u087a\0\u08c0"+
    "\0\u0906\0\u094c\0\u0992\0\u09d8\0\u0a1e\0\u0a64\0\u0aaa\0\u0af0"+
    "\0\u0b36\0\u0b7c\0\u0bc2\0\u0c08\0\u0c4e\0\u0c94\0\106\0\u0762"+
    "\0\u0cda\0\u0d20\0\u0d66\0\u0dac\0\u0df2\0\u0e38\0\u0e7e\0\u0ec4"+
    "\0\u0f0a\0\u0f50\0\u0f96\0\u0fdc\0\u1022\0\u1068\0\u10ae\0\u10f4"+
    "\0\u113a\0\u1180\0\u11c6\0\u120c\0\u1252\0\u1298\0\u12de\0\u1324"+
    "\0\u136a\0\u13b0\0\u13f6\0\u143c\0\u1482\0\u14c8\0\u0302\0\u150e"+
    "\0\u1554\0\u0302\0\u159a\0\u15e0\0\u1626\0\u166c\0\u16b2\0\u16f8"+
    "\0\u173e\0\u1784\0\u17ca\0\u1810\0\u1856\0\u189c\0\u18e2\0\u1928"+
    "\0\u196e\0\u0302\0\u0302\0\u19b4\0\u0302\0\u19fa\0\u1a40\0\u1a86"+
    "\0\u1acc\0\u1b12\0\u1b58\0\u1b9e\0\u0302\0\u0302\0\u0302\0\u1be4"+
    "\0\u1c2a\0\u1c70\0\u1cb6\0\u1cfc\0\u0302\0\u1d42\0\u0302\0\u0302"+
    "\0\u0302\0\u0302\0\u1d88\0\u0302\0\u0302\0\u1dce\0\u1e14\0\u1e5a"+
    "\0\u0302\0\u1ea0\0\u1ee6\0\u0302\0\u1f2c\0\u1f72\0\u1fb8\0\u1ffe"+
    "\0\u0302\0\u2044\0\u208a\0\u20d0\0\u2116\0\u215c\0\u21a2\0\u21e8"+
    "\0\u222e\0\u2274\0\u22ba\0\u2300\0\u2346\0\u238c\0\u23d2\0\u2418"+
    "\0\u245e\0\u0302\0\u24a4\0\u0302\0\u24ea\0\u2530\0\u2576\0\u25bc"+
    "\0\u0302\0\u2602\0\u0302";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[187];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\2\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\3\26\1\27"+
    "\5\26\1\30\1\26\1\31\3\26\1\32\1\33\3\26"+
    "\1\34\1\35\1\36\1\2\1\26\1\37\1\40\1\41"+
    "\1\42\1\26\1\43\3\26\1\44\1\26\1\45\1\26"+
    "\1\46\2\26\1\47\1\26\1\50\1\51\1\52\1\53"+
    "\107\0\2\3\107\0\1\54\101\0\5\55\1\56\100\55"+
    "\2\6\1\0\6\6\2\0\73\6\10\0\1\57\114\0"+
    "\1\60\1\0\1\20\111\0\1\61\105\0\1\62\105\0"+
    "\1\63\101\0\1\26\5\0\24\26\3\0\24\26\25\0"+
    "\1\26\5\0\1\64\12\26\1\65\2\26\1\66\5\26"+
    "\3\0\24\26\25\0\1\26\5\0\21\26\1\67\2\26"+
    "\3\0\24\26\25\0\1\26\5\0\14\26\1\70\7\26"+
    "\3\0\24\26\25\0\1\26\5\0\4\26\1\71\6\26"+
    "\1\72\10\26\3\0\24\26\25\0\1\26\5\0\1\73"+
    "\3\26\1\74\17\26\3\0\24\26\25\0\1\26\5\0"+
    "\24\26\3\0\14\26\1\75\7\26\25\0\1\26\5\0"+
    "\24\26\3\0\14\26\1\76\7\26\25\0\1\26\5\0"+
    "\24\26\3\0\16\26\1\77\5\26\25\0\1\26\5\0"+
    "\24\26\3\0\11\26\1\100\12\26\25\0\1\26\5\0"+
    "\24\26\3\0\5\26\1\101\16\26\25\0\1\26\5\0"+
    "\24\26\3\0\21\26\1\102\2\26\25\0\1\26\5\0"+
    "\24\26\3\0\14\26\1\103\7\26\25\0\1\26\5\0"+
    "\24\26\3\0\15\26\1\104\2\26\1\105\3\26\25\0"+
    "\1\26\5\0\24\26\3\0\10\26\1\106\13\26\107\0"+
    "\1\107\23\0\1\110\105\0\1\26\5\0\17\26\1\111"+
    "\4\26\3\0\24\26\25\0\1\26\5\0\20\26\1\112"+
    "\3\26\3\0\24\26\25\0\1\26\5\0\13\26\1\113"+
    "\10\26\3\0\24\26\25\0\1\26\5\0\10\26\1\114"+
    "\13\26\3\0\24\26\25\0\1\26\5\0\4\26\1\115"+
    "\17\26\3\0\24\26\25\0\1\26\5\0\2\26\1\116"+
    "\5\26\1\117\13\26\3\0\24\26\25\0\1\26\5\0"+
    "\10\26\1\120\13\26\3\0\24\26\25\0\1\26\5\0"+
    "\1\26\1\121\22\26\3\0\24\26\25\0\1\26\5\0"+
    "\22\26\1\122\1\26\3\0\24\26\25\0\1\26\5\0"+
    "\24\26\3\0\16\26\1\123\5\26\25\0\1\26\5\0"+
    "\24\26\3\0\11\26\1\124\12\26\25\0\1\26\5\0"+
    "\24\26\3\0\1\26\1\125\22\26\25\0\1\26\5\0"+
    "\24\26\3\0\5\26\1\126\16\26\25\0\1\26\5\0"+
    "\24\26\3\0\10\26\1\127\13\26\25\0\1\26\5\0"+
    "\24\26\3\0\12\26\1\130\11\26\25\0\1\26\5\0"+
    "\24\26\3\0\10\26\1\131\13\26\25\0\1\26\5\0"+
    "\24\26\3\0\5\26\1\132\16\26\25\0\1\26\5\0"+
    "\24\26\3\0\16\26\1\133\4\26\1\134\25\0\1\26"+
    "\5\0\24\26\3\0\4\26\1\135\17\26\25\0\1\26"+
    "\5\0\6\26\1\136\15\26\3\0\24\26\25\0\1\26"+
    "\5\0\20\26\1\137\3\26\3\0\24\26\25\0\1\26"+
    "\5\0\14\26\1\140\7\26\3\0\24\26\25\0\1\26"+
    "\5\0\20\26\1\141\3\26\3\0\24\26\25\0\1\26"+
    "\5\0\12\26\1\142\11\26\3\0\24\26\25\0\1\26"+
    "\5\0\20\26\1\143\3\26\3\0\24\26\25\0\1\26"+
    "\5\0\4\26\1\144\17\26\3\0\24\26\25\0\1\26"+
    "\5\0\7\26\1\145\14\26\3\0\24\26\25\0\1\26"+
    "\5\0\10\26\1\146\13\26\3\0\24\26\25\0\1\26"+
    "\5\0\20\26\1\147\3\26\3\0\24\26\25\0\1\26"+
    "\5\0\24\26\3\0\4\26\1\150\17\26\25\0\1\26"+
    "\5\0\24\26\3\0\14\26\1\151\7\26\25\0\1\26"+
    "\5\0\24\26\3\0\22\26\1\152\1\26\25\0\1\26"+
    "\5\0\24\26\3\0\12\26\1\153\11\26\25\0\1\26"+
    "\5\0\24\26\3\0\6\26\1\154\15\26\25\0\1\26"+
    "\5\0\24\26\3\0\2\26\1\155\21\26\25\0\1\26"+
    "\5\0\24\26\3\0\13\26\1\156\10\26\25\0\1\26"+
    "\5\0\24\26\3\0\3\26\1\157\20\26\25\0\1\26"+
    "\5\0\24\26\3\0\10\26\1\160\13\26\25\0\1\26"+
    "\5\0\24\26\3\0\11\26\1\161\12\26\25\0\1\26"+
    "\5\0\24\26\3\0\20\26\1\162\3\26\25\0\1\26"+
    "\5\0\4\26\1\163\17\26\3\0\24\26\25\0\1\26"+
    "\5\0\4\26\1\164\17\26\3\0\24\26\25\0\1\26"+
    "\5\0\24\26\3\0\1\165\23\26\25\0\1\26\5\0"+
    "\7\26\1\166\14\26\3\0\24\26\25\0\1\26\5\0"+
    "\24\26\3\0\1\167\23\26\25\0\1\26\5\0\7\26"+
    "\1\170\14\26\3\0\24\26\25\0\1\26\5\0\2\26"+
    "\1\171\21\26\3\0\24\26\25\0\1\26\5\0\3\26"+
    "\1\172\20\26\3\0\24\26\25\0\1\26\5\0\4\26"+
    "\1\173\17\26\3\0\24\26\25\0\1\26\5\0\24\26"+
    "\3\0\5\26\1\174\16\26\25\0\1\26\5\0\24\26"+
    "\3\0\16\26\1\175\5\26\25\0\1\26\5\0\24\26"+
    "\3\0\5\26\1\176\16\26\25\0\1\26\5\0\24\26"+
    "\3\0\7\26\1\177\14\26\25\0\1\26\5\0\24\26"+
    "\3\0\5\26\1\200\16\26\25\0\1\26\5\0\24\26"+
    "\3\0\20\26\1\201\3\26\25\0\1\26\5\0\24\26"+
    "\3\0\10\26\1\202\13\26\25\0\1\26\5\0\24\26"+
    "\3\0\13\26\1\203\10\26\25\0\1\26\5\0\24\26"+
    "\3\0\5\26\1\204\16\26\25\0\1\26\5\0\24\26"+
    "\3\0\7\26\1\205\14\26\25\0\1\26\5\0\3\26"+
    "\1\206\20\26\3\0\24\26\25\0\1\26\5\0\3\26"+
    "\1\207\20\26\3\0\24\26\25\0\1\26\5\0\15\26"+
    "\1\210\6\26\3\0\24\26\25\0\1\26\5\0\14\26"+
    "\1\211\7\26\3\0\24\26\25\0\1\26\5\0\15\26"+
    "\1\212\6\26\3\0\24\26\25\0\1\26\5\0\13\26"+
    "\1\213\10\26\3\0\24\26\25\0\1\26\5\0\20\26"+
    "\1\214\3\26\3\0\24\26\25\0\1\26\5\0\24\26"+
    "\3\0\16\26\1\215\5\26\25\0\1\26\5\0\24\26"+
    "\3\0\13\26\1\216\10\26\25\0\1\26\5\0\24\26"+
    "\3\0\20\26\1\217\3\26\25\0\1\26\5\0\24\26"+
    "\3\0\16\26\1\220\5\26\25\0\1\26\5\0\22\26"+
    "\1\221\1\222\3\0\24\26\25\0\1\26\5\0\24\26"+
    "\3\0\1\26\1\223\22\26\25\0\1\26\5\0\24\26"+
    "\3\0\6\26\1\224\15\26\25\0\1\26\5\0\24\26"+
    "\3\0\17\26\1\225\4\26\25\0\1\26\5\0\21\26"+
    "\1\226\2\26\3\0\24\26\25\0\1\26\5\0\10\26"+
    "\1\227\13\26\3\0\24\26\25\0\1\26\5\0\21\26"+
    "\1\230\2\26\3\0\24\26\25\0\1\26\5\0\12\26"+
    "\1\231\11\26\3\0\24\26\25\0\1\26\5\0\24\26"+
    "\3\0\1\232\23\26\25\0\1\26\5\0\24\26\3\0"+
    "\20\26\1\233\3\26\25\0\1\26\5\0\24\26\3\0"+
    "\11\26\1\234\12\26\25\0\1\26\5\0\4\26\1\235"+
    "\17\26\3\0\24\26\25\0\1\26\5\0\4\26\1\236"+
    "\17\26\3\0\24\26\25\0\1\26\5\0\4\26\1\237"+
    "\17\26\3\0\24\26\25\0\1\26\5\0\15\26\1\240"+
    "\6\26\3\0\24\26\25\0\1\26\5\0\24\26\3\0"+
    "\17\26\1\241\4\26\25\0\1\26\5\0\17\26\1\242"+
    "\4\26\3\0\24\26\25\0\1\26\5\0\24\26\3\0"+
    "\1\243\23\26\25\0\1\26\5\0\17\26\1\244\4\26"+
    "\3\0\24\26\25\0\1\26\5\0\21\26\1\245\2\26"+
    "\3\0\24\26\25\0\1\26\5\0\20\26\1\246\3\26"+
    "\3\0\24\26\25\0\1\26\5\0\15\26\1\247\6\26"+
    "\3\0\24\26\25\0\1\26\5\0\20\26\1\250\3\26"+
    "\3\0\24\26\25\0\1\26\5\0\4\26\1\251\17\26"+
    "\3\0\24\26\25\0\1\26\5\0\7\26\1\252\14\26"+
    "\3\0\24\26\25\0\1\26\5\0\21\26\1\253\2\26"+
    "\3\0\24\26\25\0\1\26\5\0\7\26\1\254\14\26"+
    "\3\0\24\26\25\0\1\26\5\0\17\26\1\255\4\26"+
    "\3\0\24\26\25\0\1\26\5\0\13\26\1\256\10\26"+
    "\3\0\24\26\25\0\1\26\5\0\4\26\1\257\17\26"+
    "\3\0\24\26\25\0\1\26\5\0\13\26\1\260\10\26"+
    "\3\0\24\26\25\0\1\26\5\0\20\26\1\261\3\26"+
    "\3\0\24\26\25\0\1\26\5\0\12\26\1\262\11\26"+
    "\3\0\24\26\25\0\1\26\5\0\17\26\1\263\4\26"+
    "\3\0\24\26\25\0\1\26\5\0\12\26\1\264\11\26"+
    "\3\0\24\26\25\0\1\26\5\0\7\26\1\265\14\26"+
    "\3\0\24\26\25\0\1\26\5\0\20\26\1\266\3\26"+
    "\3\0\24\26\25\0\1\26\5\0\13\26\1\267\10\26"+
    "\3\0\24\26\25\0\1\26\5\0\7\26\1\270\14\26"+
    "\3\0\24\26\25\0\1\26\5\0\12\26\1\271\11\26"+
    "\3\0\24\26\25\0\1\26\5\0\13\26\1\272\10\26"+
    "\3\0\24\26\25\0\1\26\5\0\12\26\1\273\11\26"+
    "\3\0\24\26\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[9800];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\1\1\7\11\1\1\2\11"+
    "\11\1\3\11\11\1\1\11\1\1\3\11\1\0\2\11"+
    "\1\0\3\11\23\1\1\11\164\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[187];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
     public static ArrayList<Token> listaError = new ArrayList<>();

     private void errorLexer(String lexema) {

        listaError.add(new Token(lexema, yyline + 1, yycolumn + 1, yytext(), "Error Lexico"));

     }
     private Symbol symbol(int type) {
        return new Symbol(type, yyline + 1, yycolumn + 1, yytext());
     }

     private Symbol symbol(int type, Object value) {
          return new Symbol(type, yyline + 1, yycolumn + 1, value);
     }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errorLexer(yytext());
            }
          // fall through
          case 54: break;
          case 2:
            { 
            }
          // fall through
          case 55: break;
          case 3:
            { return symbol(sym.MODULO);
            }
          // fall through
          case 56: break;
          case 4:
            { return symbol(sym.PARENTESIS_ABRE);
            }
          // fall through
          case 57: break;
          case 5:
            { return symbol(sym.PARENTESIS_CIERRA);
            }
          // fall through
          case 58: break;
          case 6:
            { return symbol(sym.MULTI);
            }
          // fall through
          case 59: break;
          case 7:
            { return symbol(sym.SUMA);
            }
          // fall through
          case 60: break;
          case 8:
            { return symbol(sym.COMA);
            }
          // fall through
          case 61: break;
          case 9:
            { return symbol(sym.RESTA);
            }
          // fall through
          case 62: break;
          case 10:
            { return symbol(sym.DIVISION);
            }
          // fall through
          case 63: break;
          case 11:
            { return symbol(sym.ENTERO, yytext());
            }
          // fall through
          case 64: break;
          case 12:
            { return symbol(sym.DOSPUNTOS);
            }
          // fall through
          case 65: break;
          case 13:
            { return symbol(sym.PUNTOCOMA);
            }
          // fall through
          case 66: break;
          case 14:
            { return symbol(sym.MENOR);
            }
          // fall through
          case 67: break;
          case 15:
            { return symbol(sym.IGUAL);
            }
          // fall through
          case 68: break;
          case 16:
            { return symbol(sym.MAYOR);
            }
          // fall through
          case 69: break;
          case 17:
            { return new Symbol(sym.VARIABLE, yyline, yycolumn, yytext());
            }
          // fall through
          case 70: break;
          case 18:
            { return symbol(sym.CORCHETE_ABRE);
            }
          // fall through
          case 71: break;
          case 19:
            { return symbol(sym.CORCHETE_CIERRA);
            }
          // fall through
          case 72: break;
          case 20:
            { return symbol(sym.POTENCIA);
            }
          // fall through
          case 73: break;
          case 21:
            { return symbol(sym.LLAVE_ABRE);
            }
          // fall through
          case 74: break;
          case 22:
            { return symbol(sym.LLAVE_CIERRA);
            }
          // fall through
          case 75: break;
          case 23:
            { return symbol(sym.NOT);
            }
          // fall through
          case 76: break;
          case 24:
            { return symbol(sym.DIFERENTE);
            }
          // fall through
          case 77: break;
          case 25:
            { return symbol(sym.CADENA, yytext());
            }
          // fall through
          case 78: break;
          case 26:
            { return symbol(sym.AND);
            }
          // fall through
          case 79: break;
          case 27:
            { return symbol(sym.MENORIGUAL);
            }
          // fall through
          case 80: break;
          case 28:
            { return symbol(sym.IGUALIGUAL);
            }
          // fall through
          case 81: break;
          case 29:
            { return symbol(sym.MAYORIGUAL);
            }
          // fall through
          case 82: break;
          case 30:
            { return symbol(sym.OR);
            }
          // fall through
          case 83: break;
          case 31:
            { return symbol(sym.DECIMAL, yytext());
            }
          // fall through
          case 84: break;
          case 32:
            { return symbol(sym.TEXT);
            }
          // fall through
          case 85: break;
          case 33:
            { return symbol(sym.DRAW);
            }
          // fall through
          case 86: break;
          case 34:
            { return symbol(sym.SOLID);
            }
          // fall through
          case 87: break;
          case 35:
            { return symbol(sym.TABLE);
            }
          // fall through
          case 88: break;
          case 36:
            { return symbol(sym.COLOR);
            }
          // fall through
          case 89: break;
          case 37:
            { return symbol(sym.WIDTH);
            }
          // fall through
          case 90: break;
          case 38:
            { return symbol(sym.DASHED);
            }
          // fall through
          case 91: break;
          case 39:
            { return symbol(sym.DOTTED);
            }
          // fall through
          case 92: break;
          case 40:
            { return symbol(sym.BORDER);
            }
          // fall through
          case 93: break;
          case 41:
            { return symbol(sym.HEIGHT);
            }
          // fall through
          case 94: break;
          case 42:
            { return new Symbol(sym.VARIABLENUMBER, yyline, yycolumn, yytext());
            }
          // fall through
          case 95: break;
          case 43:
            { return symbol(sym.POINTX);
            }
          // fall through
          case 96: break;
          case 44:
            { return symbol(sym.POINTY);
            }
          // fall through
          case 97: break;
          case 45:
            { return new Symbol(sym.VARIABLESTRING, yyline, yycolumn, yytext());
            }
          // fall through
          case 98: break;
          case 46:
            { return symbol(sym.STYLES);
            }
          // fall through
          case 99: break;
          case 47:
            { return symbol(sym.SECTION);
            }
          // fall through
          case 100: break;
          case 48:
            { return symbol(sym.SPECIAL);
            }
          // fall through
          case 101: break;
          case 49:
            { return symbol(sym.ELEMENTS);
            }
          // fall through
          case 102: break;
          case 50:
            { return symbol(sym.DROPQUESTION);
            }
          // fall through
          case 103: break;
          case 51:
            { return new Symbol(sym.OPENQUESTION, yyline, yycolumn, yytext());
            }
          // fall through
          case 104: break;
          case 52:
            { return symbol(sym.SELECTQUESTION);
            }
          // fall through
          case 105: break;
          case 53:
            { return symbol(sym.MULTIPLEQUESTION);
            }
          // fall through
          case 106: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
