// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexer.jflex

package com.example.proyecto1_compi1.analizador.form;

import java_cup.runtime.Symbol;
import java.util.ArrayList;
import com.example.proyecto1_compi1.token.Token;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING_STATE = 2;
  public static final int COMMENT_BLOCK = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2, 2
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\0\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\3\23\1\24"+
    "\6\23\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\1\65\1\66\1\67\1\70\1\71\1\72\1\0"+
    "\1\73\1\74\1\75\1\76\1\77\1\100\1\101\1\102"+
    "\1\103\1\45\1\104\1\105\1\106\1\107\1\110\1\111"+
    "\1\45\1\112\1\113\1\114\1\115\1\45\1\116\1\45"+
    "\1\117\1\45\1\120\1\121\1\122\1\123\6\0\1\3"+
    "\71\0\1\124\u0168\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\1\1\3\1\1\1\2\1\4"+
    "\1\1\1\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\23\24\1\25\1\26\1\27\13\24\1\30\1\1\1\31"+
    "\1\32\1\33\2\34\1\35\1\36\1\37\1\0\1\40"+
    "\2\2\1\41\1\0\1\42\1\0\1\43\1\44\2\0"+
    "\1\45\1\46\1\47\2\24\1\50\5\24\1\51\23\24"+
    "\1\52\11\24\1\53\1\0\1\33\1\54\1\55\2\0"+
    "\1\56\2\0\7\24\1\57\7\24\1\60\3\24\1\61"+
    "\25\24\6\0\1\24\1\62\4\24\1\63\2\24\1\64"+
    "\1\65\10\24\1\66\6\24\1\67\14\24\14\0\1\70"+
    "\4\24\1\71\7\24\1\72\1\73\1\24\1\74\1\75"+
    "\5\24\1\76\10\24\1\77\1\100\1\101\7\0\1\102"+
    "\1\103\4\0\1\24\1\104\1\105\4\24\1\106\4\24"+
    "\1\107\3\24\1\110\1\111\2\24\1\112\1\113\1\24"+
    "\1\114\1\115\1\24\6\0\1\116\1\117\1\0\1\120"+
    "\1\121\5\24\1\122\2\24\1\123\1\124\1\24\1\125"+
    "\1\24\1\126\1\24\1\127\6\0\6\24\1\130\1\131"+
    "\2\24\5\0\10\24\5\0\1\132\1\24\1\133\2\24"+
    "\1\134\3\24\1\0\1\135\1\0\4\24\1\136\1\24"+
    "\1\0\1\137\5\24\1\140\1\24\1\141\6\24\1\142"+
    "\3\24\1\143\2\24\1\144";

  private static int [] zzUnpackAction() {
    int [] result = new int[407];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\125\0\252\0\377\0\u0154\0\u01a9\0\377\0\u01fe"+
    "\0\u0253\0\377\0\u02a8\0\u02fd\0\377\0\377\0\377\0\377"+
    "\0\377\0\u0352\0\u03a7\0\u03fc\0\377\0\377\0\u0451\0\u04a6"+
    "\0\u04fb\0\377\0\u0550\0\u05a5\0\u05fa\0\u064f\0\u06a4\0\u06f9"+
    "\0\u074e\0\u07a3\0\u07f8\0\u084d\0\u08a2\0\u08f7\0\u094c\0\u09a1"+
    "\0\u09f6\0\u0a4b\0\u0aa0\0\u0af5\0\u0b4a\0\377\0\377\0\377"+
    "\0\u0b9f\0\u0bf4\0\u0c49\0\u0c9e\0\u0cf3\0\u0d48\0\u0d9d\0\u0df2"+
    "\0\u0e47\0\u0e9c\0\u0ef1\0\377\0\u0f46\0\377\0\377\0\u0f9b"+
    "\0\377\0\u0ff0\0\377\0\377\0\u1045\0\u109a\0\377\0\u10ef"+
    "\0\u1144\0\377\0\u1199\0\377\0\u11ee\0\377\0\377\0\u1243"+
    "\0\u1298\0\377\0\377\0\377\0\u12ed\0\u1342\0\u1397\0\u13ec"+
    "\0\u1441\0\u1496\0\u14eb\0\u1540\0\u0550\0\u1595\0\u15ea\0\u163f"+
    "\0\u1694\0\u16e9\0\u173e\0\u1793\0\u17e8\0\u183d\0\u1892\0\u18e7"+
    "\0\u193c\0\u1991\0\u19e6\0\u1a3b\0\u1a90\0\u1ae5\0\u1b3a\0\u1b8f"+
    "\0\u0550\0\u1be4\0\u1c39\0\u1c8e\0\u1ce3\0\u1d38\0\u1d8d\0\u1de2"+
    "\0\u1e37\0\u1e8c\0\377\0\u1ee1\0\377\0\377\0\377\0\u1f36"+
    "\0\u1f8b\0\u1243\0\u1fe0\0\u2035\0\u208a\0\u20df\0\u2134\0\u2189"+
    "\0\u21de\0\u2233\0\u2288\0\u0550\0\u22dd\0\u2332\0\u2387\0\u23dc"+
    "\0\u2431\0\u2486\0\u24db\0\u0550\0\u2530\0\u2585\0\u25da\0\u0550"+
    "\0\u262f\0\u2684\0\u26d9\0\u272e\0\u2783\0\u27d8\0\u282d\0\u2882"+
    "\0\u28d7\0\u292c\0\u2981\0\u29d6\0\u2a2b\0\u2a80\0\u2ad5\0\u2b2a"+
    "\0\u2b7f\0\u2bd4\0\u2c29\0\u2c7e\0\u2cd3\0\u2d28\0\u2d7d\0\u2dd2"+
    "\0\u2e27\0\u2e7c\0\u2ed1\0\u2f26\0\u0550\0\u2f7b\0\u2fd0\0\u3025"+
    "\0\u307a\0\u0550\0\u30cf\0\u3124\0\u0550\0\u0550\0\u3179\0\u31ce"+
    "\0\u3223\0\u3278\0\u32cd\0\u3322\0\u3377\0\u33cc\0\u0550\0\u3421"+
    "\0\u3476\0\u34cb\0\u3520\0\u3575\0\u35ca\0\u0550\0\u361f\0\u3674"+
    "\0\u36c9\0\u371e\0\u3773\0\u37c8\0\u381d\0\u3872\0\u38c7\0\u391c"+
    "\0\u3971\0\u39c6\0\u3a1b\0\u3a70\0\u3ac5\0\u3b1a\0\u3b6f\0\u3bc4"+
    "\0\u3c19\0\u3c6e\0\u3cc3\0\u3d18\0\u3d6d\0\u3dc2\0\u0550\0\u3e17"+
    "\0\u3e6c\0\u3ec1\0\u3f16\0\u0550\0\u3f6b\0\u3fc0\0\u4015\0\u406a"+
    "\0\u40bf\0\u4114\0\u4169\0\u0550\0\u0550\0\u41be\0\u0550\0\u0550"+
    "\0\u4213\0\u4268\0\u42bd\0\u4312\0\u4367\0\u0550\0\u43bc\0\u4411"+
    "\0\u4466\0\u44bb\0\u4510\0\u4565\0\u45ba\0\u460f\0\u0550\0\377"+
    "\0\377\0\u4664\0\u46b9\0\u470e\0\u4763\0\u47b8\0\u480d\0\u4862"+
    "\0\377\0\377\0\u48b7\0\u490c\0\u4961\0\u49b6\0\u4a0b\0\u0550"+
    "\0\u0550\0\u4a60\0\u4ab5\0\u4b0a\0\u4b5f\0\u0550\0\u4bb4\0\u4c09"+
    "\0\u4c5e\0\u4cb3\0\u0550\0\u4d08\0\u4d5d\0\u4db2\0\u0550\0\u0550"+
    "\0\u4e07\0\u4e5c\0\u0550\0\u0550\0\u4eb1\0\u0550\0\u0550\0\u4f06"+
    "\0\u4f5b\0\u4fb0\0\u5005\0\u505a\0\u50af\0\u5104\0\377\0\377"+
    "\0\u5159\0\377\0\u0550\0\u51ae\0\u5203\0\u5258\0\u52ad\0\u5302"+
    "\0\u0550\0\u5357\0\u53ac\0\u0550\0\u0550\0\u5401\0\u0550\0\u5456"+
    "\0\u0550\0\u54ab\0\377\0\u5500\0\u5555\0\u55aa\0\u55ff\0\u5654"+
    "\0\u56a9\0\u56fe\0\u5753\0\u57a8\0\u57fd\0\u5852\0\u58a7\0\u0550"+
    "\0\u0550\0\u58fc\0\u5951\0\u59a6\0\u59fb\0\u5a50\0\u5aa5\0\u5afa"+
    "\0\u5b4f\0\u5ba4\0\u5bf9\0\u5c4e\0\u5ca3\0\u5cf8\0\u5d4d\0\u5da2"+
    "\0\u5df7\0\u5e4c\0\u5ea1\0\u5ef6\0\u5f4b\0\377\0\u5fa0\0\u0550"+
    "\0\u5ff5\0\u604a\0\u0550\0\u609f\0\u60f4\0\u6149\0\u619e\0\377"+
    "\0\u61f3\0\u6248\0\u629d\0\u62f2\0\u6347\0\u0550\0\u639c\0\u63f1"+
    "\0\377\0\u6446\0\u649b\0\u64f0\0\u6545\0\u659a\0\u0550\0\u65ef"+
    "\0\u0550\0\u6644\0\u6699\0\u66ee\0\u6743\0\u6798\0\u67ed\0\u0550"+
    "\0\u6842\0\u6897\0\u68ec\0\u0550\0\u6941\0\u6996\0\u0550";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[407];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\1\0\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\2\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\4\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\2\33\1\44\1\45\1\33\1\46"+
    "\1\47\1\33\1\50\1\51\1\52\1\33\1\53\1\54"+
    "\1\33\1\55\1\33\1\56\1\4\1\57\1\60\1\4"+
    "\2\33\1\61\1\62\1\63\2\33\1\64\1\65\1\33"+
    "\1\66\1\33\1\67\1\70\1\71\1\33\1\72\2\33"+
    "\1\73\1\33\1\74\1\75\1\76\1\77\1\4\2\100"+
    "\1\101\1\100\1\102\1\100\1\103\23\100\1\104\1\105"+
    "\33\100\1\106\34\100\1\107\15\110\1\111\107\110\126\0"+
    "\2\5\1\0\1\5\125\0\1\112\142\0\2\113\7\0"+
    "\6\113\31\0\6\113\24\0\2\11\1\0\1\11\1\0"+
    "\120\11\12\0\1\114\135\0\2\115\121\0\1\116\120\0"+
    "\1\117\130\0\1\120\1\0\2\24\123\0\2\121\3\0"+
    "\1\122\124\0\1\123\124\0\1\124\117\0\2\33\7\0"+
    "\32\33\4\0\26\33\30\0\2\33\7\0\13\33\1\125"+
    "\16\33\4\0\26\33\30\0\2\33\7\0\24\33\1\126"+
    "\5\33\4\0\26\33\30\0\2\33\7\0\16\33\1\127"+
    "\2\33\1\130\10\33\4\0\26\33\30\0\2\33\7\0"+
    "\13\33\1\131\16\33\4\0\26\33\30\0\2\33\7\0"+
    "\16\33\1\132\13\33\4\0\26\33\30\0\2\33\7\0"+
    "\21\33\1\133\10\33\4\0\26\33\30\0\2\33\7\0"+
    "\16\33\1\134\13\33\4\0\26\33\30\0\2\33\7\0"+
    "\5\33\1\135\24\33\4\0\26\33\30\0\2\33\7\0"+
    "\10\33\1\136\21\33\4\0\26\33\30\0\2\33\7\0"+
    "\16\33\1\137\5\33\1\140\5\33\4\0\26\33\30\0"+
    "\2\33\7\0\17\33\1\141\12\33\4\0\26\33\30\0"+
    "\2\33\7\0\24\33\1\142\5\33\4\0\26\33\30\0"+
    "\2\33\7\0\4\33\1\143\25\33\4\0\26\33\30\0"+
    "\2\33\7\0\1\144\3\33\1\145\5\33\1\146\3\33"+
    "\1\147\13\33\4\0\26\33\30\0\2\33\7\0\1\150"+
    "\3\33\1\151\25\33\4\0\26\33\30\0\2\33\7\0"+
    "\4\33\1\152\25\33\4\0\26\33\30\0\2\33\7\0"+
    "\7\33\1\153\22\33\4\0\26\33\30\0\2\33\7\0"+
    "\4\33\1\154\25\33\4\0\26\33\30\0\2\33\7\0"+
    "\32\33\4\0\16\33\1\155\7\33\30\0\2\33\7\0"+
    "\32\33\4\0\20\33\1\156\5\33\30\0\2\33\7\0"+
    "\32\33\4\0\13\33\1\157\12\33\30\0\2\33\7\0"+
    "\32\33\4\0\5\33\1\160\20\33\30\0\2\33\7\0"+
    "\32\33\4\0\15\33\1\161\10\33\30\0\2\33\7\0"+
    "\32\33\4\0\1\33\1\162\24\33\30\0\2\33\7\0"+
    "\32\33\4\0\23\33\1\163\2\33\30\0\2\33\7\0"+
    "\32\33\4\0\17\33\1\164\1\165\5\33\30\0\2\33"+
    "\7\0\32\33\4\0\16\33\1\166\7\33\30\0\2\33"+
    "\7\0\32\33\4\0\17\33\1\167\2\33\1\170\3\33"+
    "\30\0\2\33\7\0\32\33\4\0\10\33\1\171\1\172"+
    "\14\33\126\0\1\173\3\0\2\100\1\0\1\100\1\0"+
    "\1\100\1\0\23\100\2\0\33\100\1\0\34\100\3\0"+
    "\1\101\210\0\1\174\36\0\2\175\3\0\1\175\1\176"+
    "\116\175\15\110\1\0\107\110\22\0\1\177\125\0\2\200"+
    "\7\0\6\200\31\0\6\200\43\0\1\201\3\0\2\115"+
    "\123\0\2\202\117\0\1\203\1\0\1\204\1\0\2\121"+
    "\123\0\2\33\7\0\1\205\23\33\1\206\5\33\4\0"+
    "\26\33\30\0\2\33\7\0\21\33\1\207\10\33\4\0"+
    "\26\33\30\0\2\33\7\0\23\33\1\210\1\211\5\33"+
    "\4\0\26\33\30\0\2\33\7\0\16\33\1\212\13\33"+
    "\4\0\26\33\30\0\2\33\7\0\22\33\1\213\7\33"+
    "\4\0\26\33\30\0\2\33\7\0\21\33\1\214\10\33"+
    "\4\0\26\33\30\0\2\33\7\0\4\33\1\215\25\33"+
    "\4\0\26\33\30\0\2\33\7\0\21\33\1\216\10\33"+
    "\4\0\26\33\30\0\2\33\7\0\15\33\1\217\14\33"+
    "\4\0\26\33\30\0\2\33\7\0\15\33\1\220\14\33"+
    "\4\0\26\33\30\0\2\33\7\0\13\33\1\221\16\33"+
    "\4\0\26\33\30\0\2\33\7\0\4\33\1\222\25\33"+
    "\4\0\26\33\30\0\2\33\7\0\21\33\1\223\10\33"+
    "\4\0\26\33\30\0\2\33\7\0\3\33\1\224\26\33"+
    "\4\0\26\33\30\0\2\33\7\0\15\33\1\225\14\33"+
    "\4\0\26\33\30\0\2\33\7\0\2\33\1\226\10\33"+
    "\1\227\16\33\4\0\26\33\30\0\2\33\7\0\30\33"+
    "\1\230\1\33\4\0\26\33\30\0\2\33\7\0\13\33"+
    "\1\231\16\33\4\0\26\33\30\0\2\33\7\0\1\33"+
    "\1\232\30\33\4\0\26\33\30\0\2\33\7\0\27\33"+
    "\1\233\2\33\4\0\26\33\30\0\2\33\7\0\21\33"+
    "\1\234\10\33\4\0\26\33\30\0\2\33\7\0\10\33"+
    "\1\235\21\33\4\0\26\33\30\0\2\33\7\0\13\33"+
    "\1\236\16\33\4\0\26\33\30\0\2\33\7\0\32\33"+
    "\4\0\15\33\1\237\2\33\1\240\5\33\30\0\2\33"+
    "\7\0\32\33\4\0\1\33\1\241\24\33\30\0\2\33"+
    "\7\0\32\33\4\0\5\33\1\242\20\33\30\0\2\33"+
    "\7\0\32\33\4\0\11\33\1\243\14\33\30\0\2\33"+
    "\7\0\32\33\4\0\2\33\1\244\23\33\30\0\2\33"+
    "\7\0\32\33\4\0\14\33\1\245\11\33\30\0\2\33"+
    "\7\0\32\33\4\0\22\33\1\246\3\33\30\0\2\33"+
    "\7\0\32\33\4\0\11\33\1\247\14\33\30\0\2\33"+
    "\7\0\32\33\4\0\11\33\1\250\14\33\30\0\2\33"+
    "\7\0\32\33\4\0\5\33\1\251\20\33\30\0\2\33"+
    "\7\0\32\33\4\0\20\33\1\252\4\33\1\253\30\0"+
    "\2\33\7\0\32\33\4\0\16\33\1\254\7\33\30\0"+
    "\2\33\7\0\32\33\4\0\4\33\1\255\21\33\32\0"+
    "\1\256\1\0\1\257\120\0\2\260\7\0\6\260\31\0"+
    "\6\260\47\0\2\261\123\0\2\262\123\0\2\263\123\0"+
    "\2\33\7\0\2\33\1\264\27\33\4\0\26\33\30\0"+
    "\2\33\7\0\4\33\1\265\25\33\4\0\26\33\30\0"+
    "\2\33\7\0\22\33\1\266\7\33\4\0\26\33\30\0"+
    "\2\33\7\0\23\33\1\267\6\33\4\0\26\33\30\0"+
    "\2\33\7\0\1\33\1\270\30\33\4\0\26\33\30\0"+
    "\2\33\7\0\17\33\1\271\12\33\4\0\26\33\30\0"+
    "\2\33\7\0\4\33\1\272\25\33\4\0\26\33\30\0"+
    "\2\33\7\0\4\33\1\273\25\33\4\0\26\33\30\0"+
    "\2\33\7\0\10\33\1\274\21\33\4\0\26\33\30\0"+
    "\2\33\7\0\4\33\1\275\25\33\4\0\26\33\30\0"+
    "\2\33\7\0\16\33\1\276\13\33\4\0\26\33\30\0"+
    "\2\33\7\0\23\33\1\277\6\33\4\0\26\33\30\0"+
    "\2\33\7\0\15\33\1\300\14\33\4\0\26\33\30\0"+
    "\2\33\7\0\17\33\1\301\12\33\4\0\26\33\30\0"+
    "\2\33\7\0\22\33\1\302\7\33\4\0\26\33\30\0"+
    "\2\33\7\0\23\33\1\303\6\33\4\0\26\33\30\0"+
    "\2\33\7\0\4\33\1\304\25\33\4\0\26\33\30\0"+
    "\2\33\7\0\10\33\1\305\21\33\4\0\26\33\30\0"+
    "\2\33\7\0\13\33\1\306\16\33\4\0\26\33\30\0"+
    "\2\33\7\0\23\33\1\307\6\33\4\0\26\33\30\0"+
    "\2\33\7\0\23\33\1\310\6\33\4\0\26\33\30\0"+
    "\2\33\7\0\13\33\1\311\7\33\1\312\6\33\4\0"+
    "\26\33\30\0\2\33\7\0\13\33\1\313\16\33\4\0"+
    "\26\33\30\0\2\33\7\0\32\33\4\0\22\33\1\314"+
    "\3\33\30\0\2\33\7\0\32\33\4\0\20\33\1\315"+
    "\5\33\30\0\2\33\7\0\32\33\4\0\24\33\1\316"+
    "\1\33\30\0\2\33\7\0\32\33\4\0\14\33\1\317"+
    "\11\33\30\0\2\33\7\0\32\33\4\0\7\33\1\320"+
    "\16\33\30\0\2\33\7\0\32\33\4\0\5\33\1\321"+
    "\20\33\30\0\2\33\7\0\32\33\4\0\2\33\1\322"+
    "\23\33\30\0\2\33\7\0\32\33\4\0\11\33\1\323"+
    "\14\33\30\0\2\33\7\0\32\33\4\0\5\33\1\324"+
    "\20\33\30\0\2\33\7\0\32\33\4\0\15\33\1\325"+
    "\10\33\30\0\2\33\7\0\32\33\4\0\3\33\1\326"+
    "\22\33\30\0\2\33\7\0\32\33\4\0\11\33\1\327"+
    "\14\33\30\0\2\33\7\0\32\33\4\0\13\33\1\330"+
    "\12\33\30\0\2\33\7\0\32\33\4\0\1\331\25\33"+
    "\30\0\2\33\7\0\32\33\4\0\22\33\1\332\3\33"+
    "\20\0\1\333\1\334\54\0\1\335\3\0\1\336\4\0"+
    "\1\337\10\0\1\340\5\0\1\341\27\0\1\342\2\0"+
    "\1\257\120\0\2\343\7\0\6\343\31\0\6\343\43\0"+
    "\1\344\3\0\2\261\117\0\1\345\1\0\1\346\1\0"+
    "\2\262\117\0\1\203\3\0\2\263\123\0\2\33\7\0"+
    "\12\33\1\347\17\33\4\0\26\33\30\0\2\33\7\0"+
    "\10\33\1\350\21\33\4\0\26\33\30\0\2\33\7\0"+
    "\4\33\1\351\25\33\4\0\26\33\30\0\2\33\7\0"+
    "\13\33\1\352\16\33\4\0\26\33\30\0\2\33\7\0"+
    "\32\33\4\0\1\353\25\33\30\0\2\33\7\0\15\33"+
    "\1\354\14\33\4\0\26\33\30\0\2\33\7\0\31\33"+
    "\1\355\4\0\26\33\30\0\2\33\7\0\10\33\1\356"+
    "\21\33\4\0\26\33\30\0\2\33\7\0\32\33\4\0"+
    "\1\357\25\33\30\0\2\33\7\0\13\33\1\360\16\33"+
    "\4\0\26\33\30\0\2\33\7\0\32\33\4\0\1\361"+
    "\25\33\30\0\2\33\7\0\10\33\1\362\21\33\4\0"+
    "\26\33\30\0\2\33\7\0\2\33\1\363\27\33\4\0"+
    "\26\33\30\0\2\33\7\0\3\33\1\364\26\33\4\0"+
    "\26\33\30\0\2\33\7\0\4\33\1\365\25\33\4\0"+
    "\26\33\30\0\2\33\7\0\10\33\1\366\21\33\4\0"+
    "\26\33\30\0\2\33\7\0\4\33\1\367\25\33\4\0"+
    "\26\33\30\0\2\33\7\0\4\33\1\370\25\33\4\0"+
    "\26\33\30\0\2\33\7\0\16\33\1\371\13\33\4\0"+
    "\26\33\30\0\2\33\7\0\32\33\4\0\5\33\1\372"+
    "\20\33\30\0\2\33\7\0\32\33\4\0\5\33\1\373"+
    "\20\33\30\0\2\33\7\0\32\33\4\0\5\33\1\374"+
    "\20\33\30\0\2\33\7\0\32\33\4\0\10\33\1\375"+
    "\15\33\30\0\2\33\7\0\32\33\4\0\13\33\1\376"+
    "\12\33\30\0\2\33\7\0\32\33\4\0\5\33\1\377"+
    "\20\33\30\0\2\33\7\0\32\33\4\0\16\33\1\u0100"+
    "\7\33\30\0\2\33\7\0\32\33\4\0\15\33\1\u0101"+
    "\10\33\30\0\2\33\7\0\32\33\4\0\22\33\1\u0102"+
    "\3\33\30\0\2\33\7\0\32\33\4\0\11\33\1\u0103"+
    "\14\33\30\0\2\33\7\0\32\33\4\0\15\33\1\u0104"+
    "\10\33\30\0\2\33\7\0\32\33\4\0\5\33\1\u0105"+
    "\20\33\30\0\2\33\7\0\32\33\4\0\11\33\1\u0106"+
    "\14\33\30\0\2\33\7\0\32\33\4\0\10\33\1\u0107"+
    "\15\33\20\0\1\333\54\0\1\u0108\50\0\1\334\53\0"+
    "\1\u0109\125\0\1\u010a\126\0\1\u010b\130\0\1\u010c\120\0"+
    "\1\u010d\3\0\1\u010e\6\0\1\u010f\5\0\1\u0110\100\0"+
    "\1\u0111\30\0\1\341\27\0\1\342\43\0\1\u0112\57\0"+
    "\2\u0113\7\0\6\u0113\31\0\6\u0113\47\0\2\u0114\123\0"+
    "\2\u0115\123\0\2\u0116\123\0\2\33\7\0\25\33\1\u0117"+
    "\4\33\4\0\26\33\30\0\2\33\7\0\3\33\1\u0118"+
    "\26\33\4\0\26\33\30\0\2\33\7\0\4\33\1\u0119"+
    "\25\33\4\0\26\33\30\0\2\33\7\0\20\33\1\u011a"+
    "\11\33\4\0\26\33\30\0\2\33\7\0\16\33\1\u011b"+
    "\13\33\4\0\26\33\30\0\2\33\7\0\17\33\1\u011c"+
    "\12\33\4\0\26\33\30\0\2\33\7\0\20\33\1\u011d"+
    "\11\33\4\0\26\33\30\0\2\33\7\0\4\33\1\u011e"+
    "\25\33\4\0\26\33\30\0\2\33\7\0\22\33\1\u011f"+
    "\7\33\4\0\26\33\30\0\2\33\7\0\16\33\1\u0120"+
    "\13\33\4\0\26\33\30\0\2\33\7\0\23\33\1\u0121"+
    "\6\33\4\0\26\33\30\0\2\33\7\0\2\33\1\u0122"+
    "\27\33\4\0\26\33\30\0\2\33\7\0\26\33\1\u0123"+
    "\3\33\4\0\26\33\30\0\2\33\7\0\32\33\4\0"+
    "\15\33\1\u0124\10\33\30\0\2\33\7\0\32\33\4\0"+
    "\3\33\1\u0125\22\33\30\0\2\33\7\0\32\33\4\0"+
    "\15\33\1\u0126\10\33\30\0\2\33\7\0\32\33\4\0"+
    "\22\33\1\u0127\3\33\30\0\2\33\7\0\32\33\4\0"+
    "\20\33\1\u0128\5\33\30\0\2\33\7\0\32\33\4\0"+
    "\15\33\1\u0129\10\33\30\0\2\33\7\0\32\33\4\0"+
    "\22\33\1\u012a\3\33\30\0\2\33\7\0\27\33\1\u012b"+
    "\1\u012c\1\33\4\0\26\33\30\0\2\33\7\0\32\33"+
    "\4\0\1\33\1\u012d\24\33\30\0\2\33\7\0\32\33"+
    "\4\0\7\33\1\u012e\16\33\30\0\2\33\7\0\32\33"+
    "\4\0\21\33\1\u012f\4\33\30\0\2\33\7\0\32\33"+
    "\4\0\21\33\1\u0130\4\33\32\0\1\u0131\213\0\1\u010a"+
    "\103\0\1\u0132\127\0\1\u0133\140\0\1\u0134\115\0\1\u0135"+
    "\114\0\1\u0136\54\0\2\u0137\7\0\6\u0137\31\0\6\u0137"+
    "\40\0\1\u0138\6\0\2\u0114\121\0\1\u0139\1\0\2\u0115"+
    "\4\0\1\u013a\112\0\1\345\3\0\2\u0116\123\0\2\33"+
    "\7\0\4\33\1\u013b\25\33\4\0\26\33\30\0\2\33"+
    "\7\0\24\33\1\u013c\5\33\4\0\26\33\30\0\2\33"+
    "\7\0\15\33\1\u013d\14\33\4\0\26\33\30\0\2\33"+
    "\7\0\13\33\1\u013e\16\33\4\0\26\33\30\0\2\33"+
    "\7\0\24\33\1\u013f\5\33\4\0\26\33\30\0\2\33"+
    "\7\0\4\33\1\u0140\25\33\4\0\26\33\30\0\2\33"+
    "\7\0\15\33\1\u0141\14\33\4\0\26\33\30\0\2\33"+
    "\7\0\32\33\4\0\1\u0142\25\33\30\0\2\33\7\0"+
    "\1\u0143\31\33\4\0\26\33\30\0\2\33\7\0\32\33"+
    "\4\0\22\33\1\u0144\3\33\30\0\2\33\7\0\32\33"+
    "\4\0\22\33\1\u0145\3\33\30\0\2\33\7\0\32\33"+
    "\4\0\22\33\1\u0146\3\33\30\0\2\33\7\0\32\33"+
    "\4\0\21\33\1\u0147\4\33\30\0\2\33\7\0\32\33"+
    "\4\0\1\33\1\u0148\24\33\30\0\2\33\7\0\32\33"+
    "\4\0\13\33\1\u0149\12\33\30\0\2\33\7\0\32\33"+
    "\4\0\1\u014a\25\33\75\0\1\u014b\146\0\1\u014c\37\0"+
    "\1\u014d\202\0\1\u014e\126\0\1\u014f\131\0\1\u0150\35\0"+
    "\2\u0151\123\0\2\33\7\0\4\33\1\u0152\25\33\4\0"+
    "\26\33\30\0\2\33\7\0\23\33\1\u0153\6\33\4\0"+
    "\26\33\30\0\2\33\7\0\4\33\1\u0154\25\33\4\0"+
    "\26\33\30\0\2\33\7\0\4\33\1\u0155\25\33\4\0"+
    "\26\33\30\0\2\33\7\0\21\33\1\u0156\10\33\4\0"+
    "\26\33\30\0\2\33\7\0\20\33\1\u0157\11\33\4\0"+
    "\26\33\30\0\2\33\7\0\13\33\1\u0158\16\33\4\0"+
    "\26\33\30\0\2\33\7\0\32\33\4\0\21\33\1\u0159"+
    "\4\33\30\0\2\33\7\0\32\33\4\0\22\33\1\u015a"+
    "\3\33\30\0\2\33\7\0\32\33\4\0\22\33\1\u015b"+
    "\3\33\121\0\1\u015c\100\0\1\u0108\144\0\1\u015d\113\0"+
    "\1\u015e\45\0\1\u015f\4\0\1\u0160\122\0\2\u0151\4\0"+
    "\1\u013a\116\0\2\33\7\0\22\33\1\u0161\7\33\4\0"+
    "\26\33\30\0\2\33\7\0\1\u0162\31\33\4\0\26\33"+
    "\30\0\2\33\7\0\32\33\4\0\1\u0163\25\33\30\0"+
    "\2\33\7\0\22\33\1\u0164\7\33\4\0\26\33\30\0"+
    "\2\33\7\0\10\33\1\u0165\21\33\4\0\26\33\30\0"+
    "\2\33\7\0\24\33\1\u0166\5\33\4\0\26\33\30\0"+
    "\2\33\7\0\32\33\4\0\11\33\1\u0167\14\33\30\0"+
    "\2\33\7\0\32\33\4\0\10\33\1\u0168\15\33\32\0"+
    "\1\u0169\214\0\1\u016a\34\0\1\u016b\122\0\2\u016c\123\0"+
    "\2\u016d\43\0\1\u016e\57\0\2\33\7\0\23\33\1\u016f"+
    "\6\33\4\0\26\33\30\0\2\33\7\0\13\33\1\u0170"+
    "\16\33\4\0\26\33\30\0\2\33\7\0\20\33\1\u0171"+
    "\11\33\4\0\26\33\30\0\2\33\7\0\23\33\1\u0172"+
    "\6\33\4\0\26\33\30\0\2\33\7\0\5\33\1\u0173"+
    "\24\33\4\0\26\33\30\0\2\33\7\0\4\33\1\u0174"+
    "\25\33\4\0\26\33\30\0\2\33\7\0\32\33\4\0"+
    "\16\33\1\u0175\7\33\30\0\2\33\7\0\32\33\4\0"+
    "\1\33\1\u0176\24\33\75\0\1\u0112\147\0\1\u0177\101\0"+
    "\1\u0109\57\0\2\u016c\43\0\1\u0178\57\0\2\u016d\1\u0179"+
    "\122\0\2\33\7\0\10\33\1\u017a\21\33\4\0\26\33"+
    "\30\0\2\33\7\0\24\33\1\u017b\5\33\4\0\26\33"+
    "\30\0\2\33\7\0\10\33\1\u017c\21\33\4\0\26\33"+
    "\30\0\2\33\7\0\22\33\1\u017d\7\33\4\0\26\33"+
    "\30\0\2\33\7\0\32\33\4\0\15\33\1\u017e\10\33"+
    "\30\0\2\33\7\0\32\33\4\0\22\33\1\u017f\3\33"+
    "\32\0\1\u0180\167\0\1\u0181\57\0\2\33\7\0\16\33"+
    "\1\u0182\13\33\4\0\26\33\30\0\2\33\7\0\4\33"+
    "\1\u0183\25\33\4\0\26\33\30\0\2\33\7\0\16\33"+
    "\1\u0184\13\33\4\0\26\33\30\0\2\33\7\0\23\33"+
    "\1\u0185\6\33\4\0\26\33\30\0\2\33\7\0\32\33"+
    "\4\0\1\u0186\25\33\75\0\1\u0111\57\0\2\33\7\0"+
    "\15\33\1\u0187\14\33\4\0\26\33\30\0\2\33\7\0"+
    "\22\33\1\u0188\7\33\4\0\26\33\30\0\2\33\7\0"+
    "\15\33\1\u0189\14\33\4\0\26\33\30\0\2\33\7\0"+
    "\10\33\1\u018a\21\33\4\0\26\33\30\0\2\33\7\0"+
    "\32\33\4\0\17\33\1\u018b\6\33\30\0\2\33\7\0"+
    "\23\33\1\u018c\6\33\4\0\26\33\30\0\2\33\7\0"+
    "\16\33\1\u018d\13\33\4\0\26\33\30\0\2\33\7\0"+
    "\32\33\4\0\16\33\1\u018e\7\33\30\0\2\33\7\0"+
    "\10\33\1\u018f\21\33\4\0\26\33\30\0\2\33\7\0"+
    "\15\33\1\u0190\14\33\4\0\26\33\30\0\2\33\7\0"+
    "\32\33\4\0\12\33\1\u0191\13\33\30\0\2\33\7\0"+
    "\16\33\1\u0192\13\33\4\0\26\33\30\0\2\33\7\0"+
    "\32\33\4\0\5\33\1\u0193\20\33\30\0\2\33\7\0"+
    "\15\33\1\u0194\14\33\4\0\26\33\30\0\2\33\7\0"+
    "\32\33\4\0\14\33\1\u0195\11\33\30\0\2\33\7\0"+
    "\32\33\4\0\16\33\1\u0196\7\33\30\0\2\33\7\0"+
    "\32\33\4\0\15\33\1\u0197\10\33\5\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[27115];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\2\1\1\11\2\1\1\11\2\1\5\11"+
    "\3\1\2\11\3\1\1\11\23\1\3\11\13\1\1\11"+
    "\1\1\2\11\1\1\1\11\1\1\2\11\1\1\1\0"+
    "\1\11\2\1\1\11\1\0\1\11\1\0\2\11\2\0"+
    "\3\11\46\1\1\11\1\0\3\11\2\0\1\1\2\0"+
    "\51\1\6\0\47\1\14\0\41\1\2\11\7\0\2\11"+
    "\4\0\32\1\6\0\2\11\1\0\1\11\20\1\1\11"+
    "\6\0\12\1\5\0\10\1\5\0\1\11\10\1\1\0"+
    "\1\11\1\0\6\1\1\0\1\11\26\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[407];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    public static ArrayList<Token> listaError = new ArrayList<>();
    private StringBuilder stringBuffer = new StringBuilder();

    private void errorLexer(String lexema) {
        listaError.add(new Token(
            lexema, yyline + 1, yycolumn + 1, lexema, "Error Léxico"
        ));
    }

    private Symbol symbol(int type) {
        return new Symbol(type, yyline + 1, yycolumn + 1, yytext());
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline + 1, yycolumn + 1, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errorLexer(yytext());
            }
          // fall through
          case 101: break;
          case 2:
            { /* ignorar */
            }
          // fall through
          case 102: break;
          case 3:
            { stringBuffer.setLength(0);
        yybegin(STRING_STATE);
            }
          // fall through
          case 103: break;
          case 4:
            { return symbol(sym.MODULO);
            }
          // fall through
          case 104: break;
          case 5:
            { return symbol(sym.PARENTESIS_ABRE);
            }
          // fall through
          case 105: break;
          case 6:
            { return symbol(sym.PARENTESIS_CIERRA);
            }
          // fall through
          case 106: break;
          case 7:
            { return symbol(sym.MULTI);
            }
          // fall through
          case 107: break;
          case 8:
            { return symbol(sym.SUMA);
            }
          // fall through
          case 108: break;
          case 9:
            { return symbol(sym.COMA);
            }
          // fall through
          case 109: break;
          case 10:
            { return symbol(sym.RESTA);
            }
          // fall through
          case 110: break;
          case 11:
            { return symbol(sym.PUNTO);
            }
          // fall through
          case 111: break;
          case 12:
            { return symbol(sym.DIVISION);
            }
          // fall through
          case 112: break;
          case 13:
            { return symbol(sym.ENTERO,  yytext());
            }
          // fall through
          case 113: break;
          case 14:
            { return symbol(sym.DOSPUNTOS);
            }
          // fall through
          case 114: break;
          case 15:
            { return symbol(sym.PUNTOCOMA);
            }
          // fall through
          case 115: break;
          case 16:
            { return symbol(sym.MENOR);
            }
          // fall through
          case 116: break;
          case 17:
            { return symbol(sym.IGUAL);
            }
          // fall through
          case 117: break;
          case 18:
            { return symbol(sym.MAYOR);
            }
          // fall through
          case 118: break;
          case 19:
            { return symbol(sym.INTERROGACION);
            }
          // fall through
          case 119: break;
          case 20:
            { return symbol(sym.VARIABLE, yytext());
            }
          // fall through
          case 120: break;
          case 21:
            { return symbol(sym.CORCHETE_ABRE);
            }
          // fall through
          case 121: break;
          case 22:
            { return symbol(sym.CORCHETE_CIERRA);
            }
          // fall through
          case 122: break;
          case 23:
            { return symbol(sym.POTENCIA);
            }
          // fall through
          case 123: break;
          case 24:
            { return symbol(sym.LLAVE_ABRE);
            }
          // fall through
          case 124: break;
          case 25:
            { return symbol(sym.LLAVE_CIERRA);
            }
          // fall through
          case 125: break;
          case 26:
            { return symbol(sym.NOT);
            }
          // fall through
          case 126: break;
          case 27:
            { stringBuffer.append(yytext());
            }
          // fall through
          case 127: break;
          case 28:
            { yybegin(YYINITIAL);
        String res = stringBuffer.toString().replace('\uFFFE', '?');
        return symbol(sym.CADENA, res);
            }
          // fall through
          case 128: break;
          case 29:
            { yybegin(YYINITIAL);
        String resultado = stringBuffer.toString();
        switch (resultado) {
            case "color":            return symbol(sym.STYLE_COLOR);
            case "background color": return symbol(sym.STYLE_BACKGROUND);
            case "font family":      return symbol(sym.STYLE_FONT);
            case "text size":        return symbol(sym.STYLE_SIZE);
            case "border":           return symbol(sym.STYLE_BORDER);
            default:
                return symbol(sym.CADENA, resultado);
        }
            }
          // fall through
          case 129: break;
          case 30:
            { stringBuffer.append('\uFFFE');
            }
          // fall through
          case 130: break;
          case 31:
            { stringBuffer.append('@');
            }
          // fall through
          case 131: break;
          case 32:
            { stringBuffer.append('¿');
            }
          // fall through
          case 132: break;
          case 33:
            { return symbol(sym.DIFERENTE);
            }
          // fall through
          case 133: break;
          case 34:
            { return symbol(sym.AND);
            }
          // fall through
          case 134: break;
          case 35:
            { return symbol(sym.RANGO);
            }
          // fall through
          case 135: break;
          case 36:
            { yybegin(COMMENT_BLOCK);
            }
          // fall through
          case 136: break;
          case 37:
            { return symbol(sym.MENORIGUAL);
            }
          // fall through
          case 137: break;
          case 38:
            { return symbol(sym.IGUALIGUAL);
            }
          // fall through
          case 138: break;
          case 39:
            { return symbol(sym.MAYORIGUAL);
            }
          // fall through
          case 139: break;
          case 40:
            { return symbol(sym.DO);
            }
          // fall through
          case 140: break;
          case 41:
            { return symbol(sym.IF);
            }
          // fall through
          case 141: break;
          case 42:
            { return symbol(sym.IN);
            }
          // fall through
          case 142: break;
          case 43:
            { return symbol(sym.OR);
            }
          // fall through
          case 143: break;
          case 44:
            { stringBuffer.append('"');
            }
          // fall through
          case 144: break;
          case 45:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 145: break;
          case 46:
            { return symbol(sym.DECIMAL, yytext());
            }
          // fall through
          case 146: break;
          case 47:
            { return symbol(sym.FOR);
            }
          // fall through
          case 147: break;
          case 48:
            { return symbol(sym.RED);
            }
          // fall through
          case 148: break;
          case 49:
            { return symbol(sym.SKY);
            }
          // fall through
          case 149: break;
          case 50:
            { return symbol(sym.BLUE);
            }
          // fall through
          case 150: break;
          case 51:
            { return symbol(sym.ELSE);
            }
          // fall through
          case 151: break;
          case 52:
            { return symbol(sym.LINE);
            }
          // fall through
          case 152: break;
          case 53:
            { return symbol(sym.MONO);
            }
          // fall through
          case 153: break;
          case 54:
            { return symbol(sym.TEXT);
            }
          // fall through
          case 154: break;
          case 55:
            { return symbol(sym.DRAW);
            }
          // fall through
          case 155: break;
          case 56:
            { return symbol(sym.BLACK);
            }
          // fall through
          case 156: break;
          case 57:
            { return symbol(sym.GREEN);
            }
          // fall through
          case 157: break;
          case 58:
            { return symbol(sym.SOLID);
            }
          // fall through
          case 158: break;
          case 59:
            { return symbol(sym.TABLE);
            }
          // fall through
          case 159: break;
          case 60:
            { return symbol(sym.WHILE);
            }
          // fall through
          case 160: break;
          case 61:
            { return symbol(sym.WHITE);
            }
          // fall through
          case 161: break;
          case 62:
            { return symbol(sym.LABEL);
            }
          // fall through
          case 162: break;
          case 63:
            { return symbol(sym.WIDTH);
            }
          // fall through
          case 163: break;
          case 64:
            { stringBuffer.append("🥲");
            }
          // fall through
          case 164: break;
          case 65:
            { stringBuffer.append("😀");
            }
          // fall through
          case 165: break;
          case 66:
            { stringBuffer.append("😐");
            }
          // fall through
          case 166: break;
          case 67:
            { stringBuffer.append("❤️");
            }
          // fall through
          case 167: break;
          case 68:
            { return symbol(sym.DOTTED);
            }
          // fall through
          case 168: break;
          case 69:
            { return symbol(sym.DOUBLE);
            }
          // fall through
          case 169: break;
          case 70:
            { return symbol(sym.PURPLE);
            }
          // fall through
          case 170: break;
          case 71:
            { return symbol(sym.YELLOW);
            }
          // fall through
          case 171: break;
          case 72:
            { return symbol(sym.HEIGHT);
            }
          // fall through
          case 172: break;
          case 73:
            { return symbol(sym.VARIABLENUMBER);
            }
          // fall through
          case 173: break;
          case 74:
            { return symbol(sym.POINTX);
            }
          // fall through
          case 174: break;
          case 75:
            { return symbol(sym.POINTY);
            }
          // fall through
          case 175: break;
          case 76:
            { return symbol(sym.VARIABLESTRING);
            }
          // fall through
          case 176: break;
          case 77:
            { return symbol(sym.STYLES);
            }
          // fall through
          case 177: break;
          case 78:
            { return symbol(sym.HEXCOLOR, yytext());
            }
          // fall through
          case 178: break;
          case 79:
            { return symbol(sym.RGB_COLOR, yytext());
            }
          // fall through
          case 179: break;
          case 80:
            { return symbol(sym.HSL_COLOR, yytext());
            }
          // fall through
          case 180: break;
          case 81:
            { return symbol(sym.CURSIVE);
            }
          // fall through
          case 181: break;
          case 82:
            { return symbol(sym.SECTION);
            }
          // fall through
          case 182: break;
          case 83:
            { return symbol(sym.CONTENT);
            }
          // fall through
          case 183: break;
          case 84:
            { return symbol(sym.CORRECT);
            }
          // fall through
          case 184: break;
          case 85:
            { return symbol(sym.OPTIONS);
            }
          // fall through
          case 185: break;
          case 86:
            { return symbol(sym.SPECIAL);
            }
          // fall through
          case 186: break;
          case 87:
            { stringBuffer.append("😺");
            }
          // fall through
          case 187: break;
          case 88:
            { return symbol(sym.VERTICAL);
            }
          // fall through
          case 188: break;
          case 89:
            { return symbol(sym.ELEMENTS);
            }
          // fall through
          case 189: break;
          case 90:
            { stringBuffer.append("⭐");
            }
          // fall through
          case 190: break;
          case 91:
            { return symbol(sym.HORIZONTAL);
            }
          // fall through
          case 191: break;
          case 92:
            { return symbol(sym.SANS_SERIF);
            }
          // fall through
          case 192: break;
          case 93:
            { String txt   = yytext();
        int    start = txt.indexOf("star-") + 5;
        int    end   = txt.lastIndexOf("]");
        int    n     = Integer.parseInt(txt.substring(start, end));
        for (int i = 0; i < n; i++) stringBuffer.append("⭐");
            }
          // fall through
          case 193: break;
          case 94:
            { return symbol(sym.ORIENTATION);
            }
          // fall through
          case 194: break;
          case 95:
            { String txt   = yytext();
        int    start = txt.indexOf("star:") + 5;
        int    end   = txt.lastIndexOf(":");
        int    n     = Integer.parseInt(txt.substring(start, end));
        for (int i = 0; i < n; i++) stringBuffer.append("⭐");
            }
          // fall through
          case 195: break;
          case 96:
            { return symbol(sym.DROPQUESTION);
            }
          // fall through
          case 196: break;
          case 97:
            { return symbol(sym.OPENQUESTION);
            }
          // fall through
          case 197: break;
          case 98:
            { return symbol(sym.SELECTQUESTION);
            }
          // fall through
          case 198: break;
          case 99:
            { return symbol(sym.MULTIPLEQUESTION);
            }
          // fall through
          case 199: break;
          case 100:
            { return symbol(sym.WHO_IS_THAT_POKEMON);
            }
          // fall through
          case 200: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
